### ISSUE TITLE
Gmail SMTP Authentication Required Error

### ISSUE THREAD

**Issue by OxyTJ** [uxbox/uxbox#1242]
**Describe the bug**
Rather than using the penpot-mailer container, I am trying to use the Gmail SMTP that I have configured with my account. However,  when creating a Penpot account, the verification email is not sent and an "Authentication Required" error (shown below) is returned, despite the credentials being correct. I have reverified over and over again that I am using the correct configuration values and that the Gmail app credentials are correct - I am using them on the same host for Postfix and I am able to send email just fine. Here is the configuration that I have that are being sent through the `environments` section of the backend container:

```
PENPOT_SMTP_ENABLED=true
PENPOT_SMTP_SSL=true
PENPOT_SMTP_TLS=true
PENPOT_SMTP_HOST='smtp.gmail.com'
PENPOT_SMTP_PORT=587
PENPOT_SMTP_USER='<my-email>@gmail.com'
PENPOT_SMTP_PASSWORD='<my-app-password>'
```

The reason it is important for me to use the Gmail (or Postfix, if possible) SMTP server rather than the provided `penpot-mailer` is because I plan on making my instance accessible for friends that will need to be able to create and verify an account without those emails being captured and not sent.

**To Reproduce**
1. Run `docker-compose up` to start  the containers (omit `-d` so that the logs are displayed in the terminal)
2. Go to the homepage
3. Click on **Create an account**
4. Enter in an **Email** and **Password**
5. Click **Create an account**
6. Enter a **Full Name**
7. Check the box that states "When creating a new account, you agree to our terms of service and privacy policy"
8. Click **Create an account**
9. Wait a couple of seconds and verify the error populates in the terminal

**Expected behavior**
Expected behavior would be to receive an account verification email to the email account that was provided to the account creation

**Desktop (please complete the following information):**

-   OS: Windows 11
-   Browser: Chrome

**Environment (please complete the following information):**
self-hosted instance

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: CentOS 7

Also provide Docker commands or docker-compose file if possible and if proceed.x

- Docker: Docker version 20.10.8, build 3967b7d
- Docker Compose: docker-compose version 1.29.2, build 5becea4c
- Docker Compose File Version: 3.5

**Backend Stack Trace (if self-hosted)**

<details>

```
[worker-47] D app.worker - action="execute task" id="5cbd5b90-1dc1-11ec-83a2-54edf9e58f23" name="sendmail" retry="0"
[worker-47] E app.worker - hint="unhandled exception on task" id="68b02270-1dc1-11ec-83a2-54edf9e58f23"
com.sun.mail.smtp.SMTPSendFailedException: 530-5.7.0 Authentication Required. Learn more at
530 5.7.0  https://support.google.com/mail/?p=WantAuthError l23sm9924040pjl.49 - gsmtp
   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2374) ~[jakarta.mail-2.0.1.jar:2.0.1]
   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1808) ~[jakarta.mail-2.0.1.jar:2.0.1]
   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1285) ~[jakarta.mail-2.0.1.jar:2.0.1]
   at jakarta.mail.Transport.send0(Transport.java:231) ~[jakarta.mail-2.0.1.jar:2.0.1]
   at jakarta.mail.Transport.send(Transport.java:150) ~[jakarta.mail-2.0.1.jar:2.0.1]
   at app.util.emails$send_BANG_.invokeStatic(emails.clj:171) ~[?:?]
   at app.util.emails$send_BANG_.invoke(emails.clj:168) ~[?:?]
   at app.emails$eval22540$fn__22541$fn__22543.invoke(emails.clj:168) ~[?:?]
   at app.metrics$wrap_summary$fn__4279.invoke(metrics.clj:249) ~[?:?]
   at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.3.jar:?]
   at clojure.lang.RestFn.applyTo(RestFn.java:132) ~[clojure-1.10.3.jar:?]
   at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
   at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.3.jar:?]
   at app.worker$handle_task.invokeStatic(worker.clj:245) ~[?:?]
   at app.worker$handle_task.invoke(worker.clj:241) ~[?:?]
   at app.worker$run_task.invokeStatic(worker.clj:288) [?:?]
   at app.worker$run_task.invoke(worker.clj:280) [?:?]
   at clojure.core$partial$fn__5859.invoke(core.clj:2634) [clojure-1.10.3.jar:?]
   at promesa.util.SupplierWrapper.get(util.cljc:37) [?:?]
   at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764) [?:?]
   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.2.jar:10.0.2]
   at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.2.jar:10.0.2]
   at java.lang.Thread.run(Thread.java:831) [?:?]
```

</details>

**Comment by Igorgro** [comment]
Did you enable "less secure aplicattions" in the account settings?

**Comment by OxyTJ** [comment]
> Did you enable "less secure aplicattions" in the account settings?

Sorry, but where is this referring to? When I go to my Google account management and App passwords, the only configuration I see is to select an app and set a device.

EDIT: A quick google search told me to go to my account settings >> `Security` and then look for `Less secure app access` at the bottom, however, I do not see it. This is a personal account, as well, so there is no administrator workspace or anything.

**Comment by Igorgro** [comment]
Yes, it should be located here: https://myaccount.google.com/security
<details>

![изображение](https://user-images.githubusercontent.com/22894169/134785377-b0441c88-2069-458d-a867-b400f869c3c3.png)
</details>

**Comment by OxyTJ** [comment]
After not seeing the **Less secure app access** section in my security settings, I did a search and found this:

![image](https://user-images.githubusercontent.com/22312051/134785606-3142b5ba-00d0-451b-8a0d-93544aef73b4.png)

Assuming that Postfix has certs or something that allows it to use my App password just fine, but that just isn't the case with Penpot?

**Comment by Igorgro** [comment]
Penpot only supports "traditional" SMTP protocol which is treated as insecure

**Comment by OxyTJ** [comment]
> Penpot only supports "traditional" SMTP protocol which is treated as insecure

Ah, ok, that is good to know. Thank you. I've been planning on writing up a Node.js SMTP server that'd also server as a mail trap in dev, so I'll go ahead and move forward with that.

Thanks again!

**Comment by niwinz** [comment]
If you need a mail catcher / trap in dev, you have this: https://github.com/sj26/mailcatcher
We are using it on penpot development enviroment. There is the docker image: https://hub.docker.com/r/sj26/mailcatcher

**Comment by OxyTJ** [comment]
> If you need a mail catcher / trap in dev, you have this: https://github.com/sj26/mailcatcher We are using it on penpot development enviroment. There is the docker image: https://hub.docker.com/r/sj26/mailcatcher

@niwinz thank you. However, my bigger concern was having a working SMTP server in production so that if I have other users connected to my server and create an account, they'd be able to verify it. My production SMTP is Postfix which goes through Gmail's SMTP.
