### ISSUE TITLE
S3 with Custom Bucket URL

### ISSUE THREAD

**Issue by tryvin** [uxbox/uxbox#1267]
**Is your feature request related to a problem? Please describe.**
Feature request only.

**Describe the solution you'd like**
I did notice you guys only allow `eu-central-1` region for S3 for now, but I think it would be huge if we could just add our own bucket url, so you can use any S3 compatible service, like Backblaze, or Scaleway Object Storage, and so on.

**Describe alternatives you've considered**
Right now I have to setup a backup to S3 for the assets local folder.

**Comment by niwinz** [comment]
Yeah, you are right. Would be awesome have it compatible with other S3 like services.
Right now is not our max priority but if I find time for it, I'll try to fix it.

In any case, this enhancement should be an easy pick for some one who wants to contribute.

**Comment by tryvin** [comment]
@niwinz I can always try to contribute if you point me to the place where the S3 backend resides. I haven't worked with Clojure yet, but I think I can do some simple changes.

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/blob/develop/backend/src/app/storage/s3.clj this is the file.

Maybe clojure and the particular architecture will look unfamiliar, but it in reality, it is very simple. We use AWS sdk, so if the SDK allows provide the URL, then, it should be pretty easy (create new configuration variables for the URL) and use this URL in the facrories of the client and presigner  (https://github.com/penpot/penpot/blob/develop/backend/src/app/storage/s3.clj#L124)

If you still thing is not approachable for you, you can justt show me for an example in java on how to initialize the client and presigner with custom URL. And having this, I will be able to implement it myself very quickly.

**Comment by tryvin** [comment]
This is basically how you do it using the S3 Java SDK

```
AmazonS3 s3 = AmazonS3ClientBuilder.standard()
     .withEndpointConfiguration(new EndpointConfiguration(
          "https://s3.eu-west-1.amazonaws.com",
          "eu-west-1"))
     .withCredentials(CREDENTIALS_PROVIDER)
     .build();
```

Everything else will basically be the same, credentials, the region should be set, the only thing we customize is the endpoint URL.

You can basically use this same way for supporting virtually all AWS regions, as the AWS endpoints are basically `https://s3.REGION.amazonaws.com` ( https://docs.aws.amazon.com/general/latest/gr/s3.html )

**Comment by niwinz** [comment]
Hmm, I think the AmazonS3ClientBuilder is from the older version, in the current version I didn't find it. 
I found only this one https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3ClientBuilder.html (which I'm already using).

**Comment by tryvin** [comment]
@niwinz Here: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/builder/SdkClientBuilder.html#endpointOverride-java.net.URI-

Methods inherited from interface software.amazon.awssdk.core.client.builder.SdkClientBuilder

And you can use this too:  https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/Region.html#of-java.lang.String-

> An instance of this class can be retrieved by referencing one of the static constants defined in this class (eg. US_EAST_1) or by using the of(String) method if the region you want is not included in this release of the SDK.

**Comment by niwinz** [comment]
Thanks, I'll put this issue on my TODO list. ;)

**Comment by emengweb** [comment]
if could use minio as custem s3 service would great!

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/1580 add support for all regions and for custom S3 providers like minio, it will be available on the next release.

**Comment by funkybunch** [comment]
Wonderful to hear @niwinz!  Any estimate yet on when that release will be cut?

**Comment by niwinz** [comment]
We probably cut the release branch in two weeks, then some time for "stabilization". But not concrete date.

**Comment by funkybunch** [comment]
@niwinz Seems like this has been merged in with the [1.12.0](https://github.com/penpot/penpot/releases/tag/1.12.0-beta) release?  Doesn't look like https://help.penpot.app/technical-guide/configuration/#storage has been updated yet.  What `.env` variables are required to get this working using Minio?

**Comment by niwinz** [comment]
```bash
export AWS_ACCESS_KEY_ID=penpot-devenv
export AWS_SECRET_ACCESS_KEY=penpot-devenv
export PENPOT_ASSETS_STORAGE_BACKEND=assets-s3
export PENPOT_STORAGE_ASSETS_S3_ENDPOINT=http://minio:9000
export PENPOT_STORAGE_ASSETS_S3_REGION=eu-central-1
export PENPOT_STORAGE_ASSETS_S3_BUCKET=penpot
```

the region is mandatory, so you should set it independently if it is used or not, I will fix this on other release

**Comment by niwinz** [comment]
and yes, we need to update the doc

**Comment by JustMitah** [comment]
Hello @niwinz,
I didn't want to open a new issue seeing as this is still open.
Is it normal that it throws an error when I try to change region to eu-east-1? it works with eu-central-1 but when I upload an image in penpot it throws an exception : 
```
[2022-06-23 13:03:38.683] E app.http.errors - Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.

software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102) ~[penpot.jar:?]
	at software.amazon.awssdk.awscore.interceptor.HelpfulUnknownHostExceptionInterceptor.modifyException(HelpfulUnknownHostExceptionInterceptor.java:59) ~[penpot.jar:?]
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyException(ExecutionInterceptorChain.java:199) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.runModifyException(ExceptionReportingUtils.java:54) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.ExceptionReportingUtils.reportFailureToInterceptors(ExceptionReportingUtils.java:38) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:49) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:159) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:103) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2158) ~[?:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:165) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]

Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: m-bucket-name.my.domain.name
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:102) ~[penpot.jar:?]
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:204) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper.setLastException(RetryableStageHelper.java:200) ~[penpot.jar:?]
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:179) ~[penpot.jar:?]
```
