### ISSUE TITLE
Error trying to use gitea as OpenID provider

### ISSUE THREAD

**Issue by luwol03** [uxbox/uxbox#1802]
Hey,

I hope you don't feal disturbed with my many issues.

Today I'm trying to setup penpot with gitea as OpenID provider.

**To Reproduce**

1.  Setup penpot as descibed in the docs
2.  Create [gitea](https://github.com/go-gitea/gitea) OAuth application
    ![image](https://user-images.githubusercontent.com/60048565/162457509-ba039d06-203c-4f00-9a1c-829334d5aecc.png)
3.  Add the openid config (see below)
4.  Try login
5.  See error

**Expected behavior**

SSO login should work

**Actual behavior**

No loging, errors in the console

**Desktop (please complete the following information):**
- OS (e.g. iOS): Windows
- Browser & version (e.g. Chrome 89.0): Chrome 100

**Environment (please complete the following information):**
- Host (e.g. https://design.penpot.app, local instance): self hosted

*If self-hosted:*
- OS Version (e.g. Ubuntu 16.04): Debian 10
- Docker / Docker-compose version (e.g. Docker version 18.03.0-ce, build 0520e24): docker
- Image version (e.g. Alpine): alpine
```
penpotapp/exporter                              latest            f565b83a2b5e   3 days ago      1.3GB
penpotapp/frontend                              latest            89031c3fe44c   3 days ago      243MB
penpotapp/backend                               latest            f47abd8f5516   3 days ago      868MB
```

Docker commands or docker-compose file (if possible and if proceed.x):
```yml
services:
 gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000 # user id des zuvor erstellten Benutzers
      - USER_GID=1000 # group id des zuvor erstellten Benutzers
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3333:3000'
    networks:
      - penpot

# .... like the example in https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml
```

Env file:
```env
PENPOT_OIDC_CLIENT_ID: "XXXX"
PENPOT_OIDC_CLIENT_SECRET: "XXXX"
PENPOT_OIDC_BASE_URI: "http://gitea:3000"
```

Logs:
<details>

```
gitea_1            | 2022/04/08 14:24:36 Completed GET /login/oauth/authorize?client_id=edd1f0d2-b373-4954-b5d7-36a3c6f79b27&redirect_uri=https%3A//fileserver/api/auth/oauth/oidc/callback&response_type=code&state=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.FJKh7TpaLVFeXVMIGZ939PTacWXUvxxhJ0GjHAsCkXc_-ePftZRTRw._ECf-THP974UTUFu.qffU2vDw4Lq_tJfqj4dIfk3RouU4L4FaNkBtchuvZvYjMYV0NyyXorlJF6gsOBu55Suz1HDT-8fHFnpdOny40boa6g.SqZHsLfF9KlXY5nvjDYxGw&scope=profile+email+openid 200 OK in 27.994064ms
gitea_1            | 2022/04/08 14:24:48 Started POST /login/oauth/grant for 192.168.2.22:50162
gitea_1            | 2022/04/08 14:24:48 Completed POST /login/oauth/grant 302 Found in 40.560841ms
penpot-frontend_1  | 172.28.0.7 - - [08/Apr/2022:14:24:48 +0000] "GET /api/auth/oauth/oidc/callback?code=g7YA0WshHHR7D68YvlnsghIUqaxpeTMsVk4HHFQFbMhN&state=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.FJKh7TpaLVFeXVMIGZ939PTacWXUvxxhJ0GjHAsCkXc_-ePftZRTRw._ECf-THP974UTUFu.qffU2vDw4Lq_tJfqj4dIfk3RouU4L4FaNkBtchuvZvYjMYV0NyyXorlJF6gsOBu55Suz1HDT-8fHFnpdOny40boa6g.SqZHsLfF9KlXY5nvjDYxGw HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows 10; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
penpot-backend_1   | [2022-04-08 14:24:48.606] W app.http.oauth - hint="unexpected error on retrieve-access-token"
penpot-backend_1   | java.net.ConnectException: null
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:555) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:119) ~[java.net.http:?]
penpot-backend_1   |    at java_http_clj.core$send.invokeStatic(core.clj:154) ~[penpot.jar:?]
penpot-backend_1   |    at java_http_clj.core$send.invoke(core.clj:148) ~[penpot.jar:?]
penpot-backend_1   |    at app.util.http$send_BANG_.invokeStatic(http.clj:25) ~[penpot.jar:?]
penpot-backend_1   |    at app.util.http$send_BANG_.invoke(http.clj:23) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_access_token.invokeStatic(oauth.clj:58) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_access_token.invoke(oauth.clj:46) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invokeStatic(oauth.clj:110) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invoke(oauth.clj:105) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$callback_handler$fn__25030.invoke(oauth.clj:242) ~[penpot.jar:?]
penpot-backend_1   |    at clojure.lang.AFn.run(AFn.java:22) ~[penpot.jar:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
penpot-backend_1   | Caused by: java.net.ConnectException
penpot-backend_1   |    at jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1038) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:197) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:229) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:205) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:205) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:239) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:471) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.checkFor407(Exchange.java:403) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Exchange.java:475) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:379) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:371) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:407) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:448) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:438) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:340) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:155) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2669) ~[?:?]
penpot-frontend_1  | 172.28.0.7 - - [08/Apr/2022:14:24:48 +0000] "GET / HTTP/1.1" 200 175957 "-" "Mozilla/5.0 (Windows 10; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:293) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:635) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:534) ~[java.net.http:?]
penpot-backend_1   |    ... 18 more
penpot-backend_1   | Caused by: java.nio.channels.ClosedChannelException
penpot-backend_1   |    at sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:195) ~[?:?]
penpot-backend_1   |    at sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:759) ~[?:?]
penpot-backend_1   |    at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:846) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$0(PlainHttpConnection.java:182) ~[java.net.http:?]
penpot-backend_1   |    at java.security.AccessController.doPrivileged(AccessController.java:554) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:184) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:229) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:205) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:205) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Http1Exchange.sendHeadersAsync(Http1Exchange.java:239) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$9(Exchange.java:471) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.checkFor407(Exchange.java:403) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.lambda$responseAsyncImpl0$10(Exchange.java:475) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsyncImpl0(Exchange.java:475) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:379) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.Exchange.responseAsync(Exchange.java:371) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:407) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.lambda$responseAsyncImpl$7(MultiExchange.java:448) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:946) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2336) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:438) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:340) ~[java.net.http:?]
penpot-frontend_1  | 172.28.0.7 - - [08/Apr/2022:14:24:48 +0000] "GET /css/main-default.css?ts=1649109239103 HTTP/1.1" 200 44746 "https://fileserver/" "Mozilla/5.0 (Windows 10; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1146) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1769) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl$DelegatingExecutor.execute(HttpClientImpl.java:155) ~[java.net.http:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture.completeAsync(CompletableFuture.java:2669) ~[?:?]
penpot-backend_1   |    at jdk.internal.net.http.MultiExchange.responseAsync(MultiExchange.java:293) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl.sendAsync(HttpClientImpl.java:635) ~[java.net.http:?]
penpot-backend_1   |    at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:534) ~[java.net.http:?]
penpot-backend_1   |    ... 18 more
penpot-backend_1   | [2022-04-08 14:24:48.733] W app.http.oauth - hint="received incomplete profile info object (please set correct scopes)" info="nil"
penpot-backend_1   | [2022-04-08 14:24:48.760] W app.http.oauth - hint="error on oauth process"
penpot-backend_1   | clojure.lang.ExceptionInfo: no user info
penpot-backend_1   |    at app.common.exceptions$error.invokeStatic(exceptions.cljc:31) ~[penpot.jar:?]
penpot-backend_1   |    at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
penpot-backend_1   |    at clojure.lang.RestFn.invoke(RestFn.java:512) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invokeStatic(oauth.clj:116) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invoke(oauth.clj:105) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$callback_handler$fn__25030.invoke(oauth.clj:242) ~[penpot.jar:?]
penpot-backend_1   |    at clojure.lang.AFn.run(AFn.java:22) ~[penpot.jar:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

</details>

Is that problem more related to gitea or penpot?

Because in the logs there is one line that shows `nil`. With my knowledge this is more some go type?
```
penpot-backend_1   | [2022-04-08 14:24:48.733] W app.http.oauth - hint="received incomplete profile info object (please set correct scopes)" info="nil"
```

Can you explain, what is missing?

If it helps somehow, here is the response of `http://fileserver:3333/.well-known/openid-configuration`:

<details>

```json
{
  "issuer": "http://fileserver:3333/",
  "authorization_endpoint": "http://fileserver:3333/login/oauth/authorize",
  "token_endpoint": "http://fileserver:3333/login/oauth/access_token",
  "jwks_uri": "http://fileserver:3333/login/oauth/keys",
  "userinfo_endpoint": "http://fileserver:3333/login/oauth/userinfo",
  "introspection_endpoint": "http://fileserver:3333/login/oauth/introspect",
  "response_types_supported": [
    "code",
    "id_token"
  ],
  "id_token_signing_alg_values_supported": [
    "RS256"
  ],
  "subject_types_supported": [
    "public"
  ],
  "scopes_supported": [
    "openid",
    "profile",
    "email",
    "groups"
  ],
  "claims_supported": [
    "aud",
    "exp",
    "iat",
    "iss",
    "sub",
    "name",
    "preferred_username",
    "profile",
    "picture",
    "website",
    "locale",
    "updated_at",
    "email",
    "email_verified",
    "groups"
  ],
  "code_challenge_methods_supported": [
    "plain",
    "S256"
  ],
  "grant_types_supported": [
    "authorization_code",
    "refresh_token"
  ]
}
```

</details>

**Comment by luwol03** [comment]
## Update:

I now figured out, that the gitea server is not reachable from within the docker network so I have to set the OAuth routes my self, so that penpot uses the internal docker network instead of the name from outside.
```yml
  PENPOT_OIDC_BASE_URI: "http://gitea:3000"
  PENPOT_OIDC_AUTH_URI: "http://myserver:3333/login/oauth/authorize"
  PENPOT_OIDC_TOKEN_URI: "http://gitea:3000/login/oauth/access_token"
  PENPOT_OIDC_USER_URI: "http://gitea:3000/login/oauth/userinfo"
```

Now I'm one step further to my issue. The first error disappeared and I have a new one:
```
gitea_1            | 2022/04/12 16:34:16 Started POST /login/oauth/grant for 192.168.X.XX:55081
gitea_1            | 2022/04/12 16:34:16 Completed POST /login/oauth/grant 302 Found in 49.817474ms
gitea_1            | 2022/04/12 16:34:18 Started POST /login/oauth/access_token for 172.28.0.8:58350
gitea_1            | 2022/04/12 16:34:18 Completed POST /login/oauth/access_token 200 OK in 425.460427ms
gitea_1            | 2022/04/12 16:34:18 Started GET /login/oauth/userinfo for 172.28.0.8:58350
gitea_1            | 2022/04/12 16:34:18 Completed GET /login/oauth/userinfo 200 OK in 11.495634ms
penpot-backend_1   | [2022-04-12 16:34:18.872] W app.http.oauth - hint="received incomplete profile info object (please set correct scopes)" info="{:backend "oidc", :email "user1@gmail.com", :fullname "", :props {:oidc/sub "2", :oidc/preferred_username "user1", :oidc/picture "http://myserver:3333/avatar/XXXXXXXXXXXXXXXXXXX", :oidc/groups nil}}"
penpot-frontend_1  | 172.28.0.7 - - [12/Apr/2022:16:34:18 +0000] "GET /api/auth/oauth/oidc/callback?code=iBWUczDIn0i61WzYPJV3K9GMGul0K1LDos3lu8Vq9a23&state=eyJhbGciOiJBMjU2S1ciLCJlbmMiOiJBMjU2R0NNIn0.lKp9VDLQl2sBP8ivUQR3-ERVMD3AXq4s4oRfDYV_eW-nIaeY8NhBAA.V8a0d-a55e0DGr9g.VBIgx_nflfx5oEewqjhnZvkgMXDLwJikVR4zeipx80qD1ns1TC4CsdOJweDqtnySaS-2diuxzG2uJr9x_qH9D2Grlg.Gez1f3hiz3MokCWRbpe6FQ HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 10; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
penpot-backend_1   | [2022-04-12 16:34:18.885] W app.http.oauth - hint="error on oauth process"
penpot-backend_1   | clojure.lang.ExceptionInfo: no user info
penpot-backend_1   |    at app.common.exceptions$error.invokeStatic(exceptions.cljc:31) ~[penpot.jar:?]
penpot-backend_1   |    at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
penpot-backend_1   |    at clojure.lang.RestFn.invoke(RestFn.java:512) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invokeStatic(oauth.clj:116) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$retrieve_info.invoke(oauth.clj:105) ~[penpot.jar:?]
penpot-backend_1   |    at app.http.oauth$callback_handler$fn__25030.invoke(oauth.clj:242) ~[penpot.jar:?]
penpot-backend_1   |    at clojure.lang.AFn.run(AFn.java:22) ~[penpot.jar:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?]
penpot-backend_1   |    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
```

From what I see, now penpot doesn't like the profile information which gitea returns. 

Doing the OAuth requests manually results with the following:
`http://myserver:3333/login/oauth/userinfo`:
```json
{
    "sub": "2",
    "name": "",
    "preferred_username": "user1",
    "email": "user1@gmail.com",
    "picture": "http://myserver:3333/avatar/XXXXXXXXXXXXXXXXXX",
    "groups": null
}
```

## Workaround / Improvement Idea

Now I found out, that if I set the name of my account, the response returns the following. 
```json
{
    "sub": "2",
    "name": "user1 full name",
    "preferred_username": "user1",
    "email": "user1@gmail.com",
    "picture": "http://myserver:3333/avatar/XXXXXXXXXXXXX",
    "groups": null
}
```

Now penpot is able to use gitea as an OAuth provider. 

However I think this should be improved somehow. I can think of two cases (maybe also both side by side):
1. I should be able to tell penpot which claim he should use for id, email, username and profile (like I can do it in wikijs)
    ![image](https://user-images.githubusercontent.com/60048565/163015593-853186dc-06c6-4070-8840-fc9de2964aba.png)
2. Gitea should return the normal username by default for the name claim if nothing is set

**Comment by niwinz** [comment]
Sorry for my late response,
As I guess you have discovered, the last error is because the name is EMPTY. We can think in relax this rule but this is not going to be released "soon". I will put it on my task list and in some future I will relax this rule. Meanwhile I think it should be fixed on the OIDC provider. The `profile` scope makes the `name` mandatory and we expect it to be present and not empty.

**Comment by luwol03** [comment]
Ok. Meanwhile after I discovered the real problem, I also opened an issue on giteas side: https://github.com/go-gitea/gitea/issues/19382
