### ISSUE TITLE
bug: Azure AD Authentication suck on : Approval required

### ISSUE THREAD

**Issue by Rod-O** [uxbox/uxbox#2500]
### Steps To Reproduce

Setup OpenID with Azure AD

### Expected behavior

Normal approval

### Actual behavior

Some users are asked for Approval, some aren't, log show errors on the backend

### Screenshots or video

![image](https://user-images.githubusercontent.com/259931/197236309-4a4ee207-781f-4225-acce-b084442fdaa6.png)

### Backend Stack Trace

```console
[2022-10-20 19:05:34.778] E app.auth.oidc - hint="error on oauth process"
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
	at java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
	at java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
	at java.util.regex.Pattern.matcher(Pattern.java:1144) ~[?:?]
	at java.util.regex.Pattern.split(Pattern.java:1272) ~[?:?]
	at clojure.string$split.invokeStatic(string.clj:227) ~[penpot.jar:?]
	at clojure.string$split.invoke(string.clj:219) ~[penpot.jar:?]
	at buddy.sign.jwe$split_jwe_message.invokeStatic(jwe.clj:196) ~[penpot.jar:?]
	at buddy.sign.jwe$split_jwe_message.invoke(jwe.clj:194) ~[penpot.jar:?]
	at buddy.sign.jwe$decrypt.invokeStatic(jwe.clj:238) ~[penpot.jar:?]
	at buddy.sign.jwe$decrypt.invoke(jwe.clj:234) ~[penpot.jar:?]
	at app.tokens$decode.invokeStatic(tokens.clj:31) ~[penpot.jar:?]
	at app.tokens$decode.invoke(tokens.clj:29) ~[penpot.jar:?]
	at app.tokens$verify.invokeStatic(tokens.clj:36) ~[penpot.jar:?]
	at app.tokens$verify.invoke(tokens.clj:34) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:396) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-20 19:05:38.501] E app.auth.oidc - hint="error on oauth process"
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "this.text" is null
	at java.util.regex.Matcher.getTextLength(Matcher.java:1769) ~[?:?]
	at java.util.regex.Matcher.reset(Matcher.java:415) ~[?:?]
	at java.util.regex.Matcher.<init>(Matcher.java:252) ~[?:?]
	at java.util.regex.Pattern.matcher(Pattern.java:1144) ~[?:?]
	at java.util.regex.Pattern.split(Pattern.java:1272) ~[?:?]
	at clojure.string$split.invokeStatic(string.clj:227) ~[penpot.jar:?]
	at clojure.string$split.invoke(string.clj:219) ~[penpot.jar:?]
	at buddy.sign.jwe$split_jwe_message.invokeStatic(jwe.clj:196) ~[penpot.jar:?]
	at buddy.sign.jwe$split_jwe_message.invoke(jwe.clj:194) ~[penpot.jar:?]
	at buddy.sign.jwe$decrypt.invokeStatic(jwe.clj:238) ~[penpot.jar:?]
	at buddy.sign.jwe$decrypt.invoke(jwe.clj:234) ~[penpot.jar:?]
	at app.tokens$decode.invokeStatic(tokens.clj:31) ~[penpot.jar:?]
	at app.tokens$decode.invoke(tokens.clj:29) ~[penpot.jar:?]
	at app.tokens$verify.invokeStatic(tokens.clj:36) ~[penpot.jar:?]
	at app.tokens$verify.invoke(tokens.clj:34) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:396) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-20 19:07:39.324] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-20 20:00:00.029] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-20 21:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-20 22:00:00.022] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-20 23:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 00:00:00.118] I app.tasks.objects-gc - hint="objects gc finished succesfully", min-age="168h", total=0
[2022-10-21 00:00:00.121] I app.storage - hint="task finished", task="gc-touched", to-freeze=1, to-delete=0
[2022-10-21 00:00:00.125] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 00:00:00.126] I app.storage - hint="task finished", min-age="2h", task="gc-deleted", total=0
[2022-10-21 00:06:14.225] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-21 00:14:42.546] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-21 00:14:50.053] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-21 00:31:28.922] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-21 01:00:00.016] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 02:00:00.034] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 02:00:00.042] I app.tasks.file-gc - hint="task finished", min-age="168h", total=0
[2022-10-21 03:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 04:00:00.019] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 05:00:00.025] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 06:00:00.024] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 07:00:00.022] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 08:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 09:00:00.022] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 10:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 11:00:00.022] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 12:00:00.020] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 13:00:00.027] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 14:00:00.021] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2022-10-21 14:37:46.634] E app.auth.oidc - hint="error on oauth process"
clojure.lang.ExceptionInfo: :internal
	at app.common.exceptions$error.invokeStatic(exceptions.cljc:32) ~[penpot.jar:?]
	at app.common.exceptions$error.doInvoke(exceptions.cljc:25) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:619) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invokeStatic(oidc.clj:389) ~[penpot.jar:?]
	at app.auth.oidc$retrieve_info.invoke(oidc.clj:356) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182$fn__20183.invoke(oidc.clj:479) ~[penpot.jar:?]
	at promesa.util.FunctionWrapper.apply(util.cljc:43) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1187) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2309) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:144) ~[?:?]
	at promesa.impl$fn__16402.invokeStatic(impl.cljc:124) ~[penpot.jar:?]
	at promesa.impl$fn__16402.invoke(impl.cljc:110) ~[penpot.jar:?]
	at promesa.protocols$fn__15157$G__15077__15170.invoke(protocols.cljc:28) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler$process_request__20182.invoke(oidc.clj:479) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invokeStatic(oidc.clj:487) ~[penpot.jar:?]
	at app.auth.oidc$callback_handler.invoke(oidc.clj:476) ~[penpot.jar:?]
	at app.auth.oidc$fn__20203$fn__20204$fn__20206.invoke(oidc.clj:497) ~[penpot.jar:?]
	at app.http.middleware$fn__17528$fn__17529$fn__17530.invoke(middleware.clj:215) ~[penpot.jar:?]
	at app.http.middleware$fn__17520$fn__17521$fn__17522$fn__17523.invoke(middleware.clj:204) ~[penpot.jar:?]
	at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
[2022-10-21 15:00:00.025] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
```

**Comment by niwinz** [comment]
Hmm at first look, the exception indicates that azure is returning unexpected data. Is a known issue that Azure is not very compliant with OIDC, there are maybe some particularities that makes it fail, but I don't know how I can help.

The first error means the Azure is not returning correctly the state token (something that can't happen in a compliant OIDC impl, as far as I know, in any case I take a note to make this fail better)
The second kind of errors means Azure is returning an error directly, so I think is not penpot related.

**Comment by hirunatan** [comment]
Closing due to inactivity. Please reopen it if necessary.
