### ISSUE TITLE
An error occurred during project development environment launch

### ISSUE THREAD

**Issue by SimsonW** [uxbox/uxbox#2593]
### **Steps To Reproduce**
After a fresh and clean installation of the latest version of Penpot on my Mac，an error occurred during project launch

### **Expected behavior**
Regular login and running the project.

### **Actual behavior**
I found this log during project launch:

```
MikedeMacBook-Pro:frontend mike$ npm run test

> app@0.1.0 test /Users/mike/Downloads/penpot-develop/frontend
> yarn run compile-test && yarn run run-test

yarn run v1.21.1
$ clojure -M:dev:shadow-cljs compile test --config-merge '{:autorun false}'
--- SHADOW-CLJS FAILED TO LOAD! ----------------------

This is most commonly caused by a dependency conflict.
When using deps.edn or project.clj you must ensure that all
required dependencies are provided with the correct version.

You are using shadow-cljs version: 2.20.2

The important dependencies are:

  org.clojure/clojure "1.11.1"
  org.clojure/clojurescript "1.11.60"
  com.google.javascript/closure-compiler-unshaded "v20220803"

Please verify that you are loading these versions.
You can find all required dependencies here:

  https://clojars.org/thheller/shadow-cljs/versions/2.20.2

Please refer to the Guide for more information:

  https://shadow-cljs.github.io/docs/UsersGuide.html#failed-to-load

-----------------------------------------------------

The error encountered was:

Syntax error macroexpanding at (shadow/cljs/util.clj:1:1).
        at clojure.lang.Compiler.load(Compiler.java:7665)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at clojure.core$load_one.invoke(core.clj:5928)
        at clojure.core$load_lib$fn__6850.invoke(core.clj:5975)
        at clojure.core$load_lib.invokeStatic(core.clj:5974)
        at clojure.core$load_lib.doInvoke(core.clj:5953)
        at clojure.lang.RestFn.applyTo(RestFn.java:142)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$load_libs.invokeStatic(core.clj:6016)
        at clojure.core$load_libs.doInvoke(core.clj:6000)
        at clojure.lang.RestFn.applyTo(RestFn.java:137)
        at clojure.core$apply.invokeStatic(core.clj:669)
        at clojure.core$require.invokeStatic(core.clj:6038)
        at clojure.core$require.doInvoke(core.clj:6038)
        at clojure.lang.RestFn.invoke(RestFn.java:551)
        at shadow.cljs.devtools.config$eval191$loading__6789__auto____192.invoke(config.clj:1)
        at shadow.cljs.devtools.config$eval191.invokeStatic(config.clj:1)
        at shadow.cljs.devtools.config$eval191.invoke(config.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:7194)
        at clojure.lang.Compiler.eval(Compiler.java:7183)
        at clojure.lang.Compiler.load(Compiler.java:7653)
        at clojure.lang.RT.loadResourceScript(RT.java:381)
        at clojure.lang.RT.loadResourceScript(RT.java:372)
        at clojure.lang.RT.load(RT.java:459)
        at clojure.lang.RT.load(RT.java:424)
        at clojure.core$load$fn__6908.invoke(core.clj:6161)
        at clojure.core$load.invokeStatic(core.clj:6160)
        at clojure.core$load.doInvoke(core.clj:6144)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.core$load_one.invokeStatic(core.clj:5933)
        at cloj
```
I found the error might be caused by the wrong version of the dependency **com.google.javascript/closure-compiler-unshaded**, the version of mine was **v20220502**:

I've tried install  the dependency with correct version  **v20220803**, how ever it did not take effect and showed the same error log.

### **Environment (please complete the following information)**
MacOS 12.6.1(21G217)

**Comment by niwinz** [comment]
You are trying to start devenv, and looks there are some issues, I will look on it. But if your intention is start the project for using it and not develop, the correct apprach is: https://help.penpot.app/technical-guide/getting-started/#install-with-docker

**Comment by SimsonW** [comment]
Thanks a lot!
