### ISSUE TITLE
bug: Docker backend container was shutdown several times in a week

### ISSUE THREAD

**Issue by holycrypto** [uxbox/uxbox#2783]
### Steps To Reproduce

1. docker compose up -d
2. Backend container was shutdown
3. Restart penpot-backend container
4. Backend container was shutdown again

### Expected behavior

Container is running normally

### Actual behavior

Here is container logs:
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/30022286/212649514-8fc1fd6f-f5a1-4b51-a008-d9aae9e028db.png">

### Smartphone (please complete the following information)

- MacBook Pro 2019
- Chrome Browser

### Environment (please complete the following information)

- MacOS  Darwin 21.5.0
- Docker Compose version v2.0.0-rc.1
- Docker Client: 20.10.8
- Docker Engine: Community (20.10.8 )

### Backend Stack Trace

```console
[2023-01-11 20:59:57.571] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-11 21:00:00.005] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-11 21:29:54.960] E app.worker - hint="unhandled exception on scheduled task", task-id="telemetry"
java.io.IOException: Connection reset
	at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:584) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
	at java_http_clj.core$send.invokeStatic(core.clj:154) ~[penpot.jar:?]
	at java_http_clj.core$send.invoke(core.clj:148) ~[penpot.jar:?]
	at app.http.client$fn__16363$send__16366.invoke(client.clj:30) ~[penpot.jar:?]
	at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[penpot.jar:?]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[penpot.jar:?]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[penpot.jar:?]
	at clojure.lang.RestFn.invoke(RestFn.java:421) ~[penpot.jar:?]
	at app.tasks.telemetry$send_BANG_.invokeStatic(telemetry.clj:84) ~[penpot.jar:?]
	at app.tasks.telemetry$send_BANG_.invoke(telemetry.clj:82) ~[penpot.jar:?]
	at app.tasks.telemetry$fn__33671$fn__33674.invoke(telemetry.clj:60) ~[penpot.jar:?]
	at app.worker$wrap_task_handler$fn__16221.invoke(worker.clj:574) ~[penpot.jar:?]
	at app.worker$execute_cron_task$run_task__16184.invoke(worker.clj:532) ~[penpot.jar:?]
	at app.worker$execute_cron_task$handle_task__16194$fn__16195.invoke(worker.clj:537) ~[penpot.jar:?]
	at next.jdbc.transaction$transact_STAR_.invokeStatic(transaction.clj:72) ~[penpot.jar:?]
	at next.jdbc.transaction$transact_STAR_.invoke(transaction.clj:51) ~[penpot.jar:?]
	at next.jdbc.transaction$fn__6476.invokeStatic(transaction.clj:136) ~[penpot.jar:?]
	at next.jdbc.transaction$fn__6476.invoke(transaction.clj:115) ~[penpot.jar:?]
	at next.jdbc.protocols$fn__5309$G__5304__5318.invoke(protocols.clj:58) ~[penpot.jar:?]
	at next.jdbc$transact.invokeStatic(jdbc.clj:381) ~[penpot.jar:?]
	at next.jdbc$transact.invoke(jdbc.clj:373) ~[penpot.jar:?]
	at app.worker$execute_cron_task$handle_task__16194.invoke(worker.clj:536) ~[penpot.jar:?]
	at clojure.lang.AFn.run(AFn.java:22) ~[penpot.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.net.SocketException: Connection reset
	at sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426) ~[?:?]
	at jdk.internal.net.http.SocketTube.readAvailable(SocketTube.java:1170) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:833) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303) ~[java.net.http:?]
	at jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957) ~[java.net.http:?]
	at jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:977) ~[java.net.http:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:932) ~[java.net.http:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:932) ~[java.net.http:?]
[2023-01-11 21:59:57.587] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-11 22:00:00.003] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-11 22:59:57.555] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-11 23:00:00.003] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
```

**Comment by niwinz** [comment]
Thanks for porting the exception, looks related to an other issue we have tracked internally.
In any case, the problem you describe (docker container shutdown, looks unrelated to this trace) and there are no evidence on logs that that is caused by something from penpot side.

**Comment by niwinz** [comment]
closing for inactivity
