### ISSUE TITLE
bug: Internal error then blank page after trying to export to pdf

### ISSUE THREAD

**Issue by ElMahdiAboulmanadel** [uxbox/uxbox#2818]
### Steps To Reproduce

I just finished a design in Penpot, I clicked on the three dots then tried to export it to PDF. It was stuck at 0/8 then it showed an internal error. When I refreshed the page it became blank. I tried to access Penpot from other devices but still get the same blank page. 

### Expected behavior

I was expecting it to export the PDF

### Actual behavior

Blank page

### Screenshots or video

![Capture](https://user-images.githubusercontent.com/84625924/213769016-95e9cafa-0d0f-4fc8-8d42-ff52d2f8474e.PNG)

### Desktop (please complete the following information)

- OS : windows, macos and linux (Tried everywhere)

### Smartphone (please complete the following information)

Smartphones too

### Environment (please complete the following information)

Self-hosted : 
OS : Ubuntu 18.04
Docker containers

### Additional context

I hope I didn't lose my designs

**Comment by ElMahdiAboulmanadel** [comment]
Here is what I found in the backend logs : 
[2023-01-20 15:00:00.011] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-20 16:00:00.011] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-20 17:00:00.026] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0
[2023-01-20 17:26:58.774] W app.worker - hint="connection error, trying resume in some instants"
Exception in thread "async-dispatch-5" java.lang.ClassCastException: class java.time.Duration cannot be cast to class java.lang.Number (java.time.Duration and java.lang.Number are in module java.base of loader 'bootstrap')
        at app.worker$event_loop$fn__15817$state_machine__12251__auto____15832$fn__15834.invoke(worker.clj:197)
        at app.worker$event_loop$fn__15817$state_machine__12251__auto____15832.invoke(worker.clj:197)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
        at clojure.core.async$ioc_alts_BANG_$fn__12480.invoke(async.clj:421)
        at clojure.core.async$do_alts$fn__12419$fn__12422.invoke(async.clj:288)
        at clojure.core.async.impl.channels.ManyToManyChannel$fn__7092$fn__7093.invoke(channels.clj:99)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at clojure.core.async.impl.concurrent$counted_thread_factory$reify__6995$fn__6996.invoke(concurrent.clj:29)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ElMahdiAboulmanadel** [comment]
The postgres container logs : 
2023-01-20 17:26:39.935 UTC [68] LOG:  could not close temporary statistics file "pg_stat_tmp/db_0.tmp": No space left on device
2023-01-20 17:26:39.935 UTC [68] LOG:  could not close temporary statistics file "pg_stat_tmp/global.tmp": No space left on device
2023-01-20 17:26:46.078 UTC [64] PANIC:  could not write to file "pg_logical/replorigin_checkpoint.tmp": No space left on device
2023-01-20 17:26:46.091 UTC [1] LOG:  checkpointer process (PID 64) was terminated by signal 6: Aborted
2023-01-20 17:26:46.091 UTC [1] LOG:  terminating any other active server processes
2023-01-20 17:26:46.100 UTC [68] LOG:  could not write temporary statistics file "pg_stat/db_16384.tmp": No space left on device
2023-01-20 17:26:46.101 UTC [68] LOG:  could not write temporary statistics file "pg_stat/db_13757.tmp": No space left on device
2023-01-20 17:26:46.103 UTC [68] LOG:  could not close temporary statistics file "pg_stat/db_0.tmp": No space left on device
2023-01-20 17:26:46.103 UTC [68] LOG:  could not close temporary statistics file "pg_stat/global.tmp": No space left on device
2023-01-20 17:26:46.106 UTC [1] LOG:  all server processes terminated; reinitializing
2023-01-20 17:26:46.149 UTC [26944] LOG:  database system was interrupted; last known up at 2023-01-20 17:23:12 UTC
2023-01-20 17:26:46.201 UTC [26944] LOG:  database system was not properly shut down; automatic recovery in progress
2023-01-20 17:26:46.204 UTC [26944] LOG:  redo starts at 0/67FC8810
2023-01-20 17:26:46.221 UTC [26944] FATAL:  could not extend file "base/16384/17386": No space left on device
2023-01-20 17:26:46.221 UTC [26944] HINT:  Check free disk space.
2023-01-20 17:26:46.221 UTC [26944] CONTEXT:  WAL redo at 0/6825FEC8 for Heap2/PRUNE: latestRemovedXid 9722 nredirected 0 ndead 4; blkref #0: rel 1663/16384/17386, blk 1877 FPW
2023-01-20 17:26:46.223 UTC [1] LOG:  startup process (PID 26944) exited with exit code 1
2023-01-20 17:26:46.223 UTC [1] LOG:  aborting startup due to startup process failure
2023-01-20 17:26:46.227 UTC [1] LOG:  database system is shut down

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-01-20 17:26:47.344 UTC [1] FATAL:  could not write lock file "postmaster.pid": No space left on device

**Comment by niwinz** [comment]
Looks like you postgresql can't start because no space left, there we can't do nothing from our side.
About the backend exception, I will look on it, but looks unrelated, pdf exportation does not touches backend.

Can you try to pull the latest version and check if this still hapens?

**Comment by hirunatan** [comment]
Closing due to inactivity. Please reopen it if necessary.
