### ISSUE TITLE
bug: Unexpected error on export multiple

### ISSUE THREAD

**Issue by keindev** [uxbox/uxbox#3015]
### Steps To Reproduce

1. Open penpot and create new project (new instance 1.17.1, same on 1.17.2)
2. create any simple figure
3. try to export as `svg` 
4. error in exporter log:

```
SEV [app.handlers.export-shapes] hint="unexpected error on export multiple"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
```

### Expected behavior

Export `svg` file (or any)

### Actual behavior

Actually I'm not sure if this is a bug. However, I have configured `PENPOT_PUBLIC_URI` for the exporter (like in docker-compose) and the frontend is accessible from the exporter pod.

Backaend see `redis` and `postgres`, frontend see backend. All fine, only export error. 

Downloading as `.penpot` or as `.svg + .json` works.

I try set `PENPOT_TENANT: pro` like in #2470 but it's not help.

### Screenshots or video

https://user-images.githubusercontent.com/4527292/223228583-f021b543-0df6-4f08-a6b9-35157d2544f6.mp4

### Desktop (please complete the following information)

- OS Ubuntu
- Chrome Version 110.0.5481.177 (Official Build) (64-bit)
- Original images from docker v1.17.1 (exporter, frontend and backend)

### Environment (please complete the following information)

Set to backend and frontend:
- PENPOT_PUBLIC_URI=http://localhost:80
- PENPOT_DATABASE_URI=postgresql://postgres.penpot:5432/penpot
- PENPOT_SECRET_KEY=somekey
- PENPOT_REDIS_URI=redis://redis.penpot:6379/0
- PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
- PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
- PENPOT_HTTP_SERVER_HOST=0.0.0.0
- PENPOT_FLAGS="disable-secure-session-cookies disable-insecure-register disable-registration enable-login disable-email-verification enable-backend-api-docs"
- PENPOT_TELEMETRY_ENABLED="false"

Set to exporter:
- PENPOT_PUBLIC_URI=http://frontend.penpot:80
- PENPOT_REDIS_URI=redis://redis.penpot:6379/0

Nginx conf

```
user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    include /etc/nginx/modules-enabled/*.conf;

    events {
        worker_connections 2048;
        # multi_accept on;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_requests 30;
        keepalive_timeout 65;
        types_hash_max_size 2048;

        server_tokens off;

        reset_timedout_connection on;
        client_body_timeout 30s;
        client_header_timeout 30s;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        error_log /dev/stdout;
        access_log /dev/stdout;

        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_static on;
        gzip_comp_level 4;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;

        gzip_types text/plain text/css text/javascript application/javascript application/json application/transit+json;

        resolver 127.0.0.11;

        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }

        server {
            listen 80 default_server;
            server_name _;

            client_max_body_size 100M;
            charset utf-8;

            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

            etag off;
            root /var/www/app/;

            location ~* \.(js|css).*$ {
                add_header Cache-Control "max-age=86400" always; # 24 hours
            }

            location ~* \.(html).*$ {
                add_header Cache-Control "no-cache, max-age=0" always;
            }

            location /api/export {
                proxy_pass http://exporter.penpot:6061;
            }

            location /api {
                proxy_pass http://backend.penpot:6060/api;
            }

            location /ws/notifications {
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_pass http://backend.penpot:6060/ws/notifications;
            }

            location @handle_redirect {
                set $redirect_uri "$upstream_http_location";
                set $redirect_host "$upstream_http_x_host";
                set $redirect_cache_control "$upstream_http_cache_control";

                proxy_buffering off;

                proxy_set_header Host "$redirect_host";
                proxy_hide_header etag;
                proxy_hide_header x-amz-id-2;
                proxy_hide_header x-amz-request-id;
                proxy_hide_header x-amz-meta-server-side-encryption;
                proxy_hide_header x-amz-server-side-encryption;
                proxy_pass $redirect_uri;

                add_header x-internal-redirect "$redirect_uri";
                add_header x-cache-control "$redirect_cache_control";
                add_header cache-control "$redirect_cache_control";
            }

            location /assets {
                proxy_pass http://backend.penpot:6060/assets;
                recursive_error_pages on;
                proxy_intercept_errors on;
                error_page 301 302 307 = @handle_redirect;
            }

            location /internal/assets {
                internal;
                alias /opt/data/assets;
                add_header x-internal-redirect "$upstream_http_x_accel_redirect";
            }
        }
    }
    ```
    

### Frontend Stack Trace

```console
--[06/Mar/2023:20:49:59 +0000] "POST /api/rpc/command/create-file HTTP/1.1" 200 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "POST /api/rpc/command/get-comment-threads HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/query/project?id=de21e813-c357-8168-8002-296be0081a56 HTTP/1.1" 200 161 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/command/get-team-users?file-id=de21e813-c357-8168-8002-29702475cfe6 HTTP/1.1" 200 100 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/command/get-file?id=de21e813-c357-8168-8002-29702475cfe6&features=storage/pointer-map HTTP/1.1" 200 378 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/command/get-file-object-thumbnails?file-id=de21e813-c357-8168-8002-29702475cfe6 HTTP/1.1" 200 37 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "POST /api/rpc/command/get-profiles-for-file-comments HTTP/1.1" 200 139 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/query/font-variants?team-id=de21e813-c357-8168-8002-296be00783e2 HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:49:59 +0000] "GET /api/rpc/command/get-file-libraries?file-id=de21e813-c357-8168-8002-29702475cfe6&features=storage/pointer-map HTTP/1.1" 200 33 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:04 +0000] "POST /api/rpc/command/update-file HTTP/1.1" 200 519 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:07 +0000] "POST /api/rpc/command/update-file HTTP/1.1" 200 262 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:08 +0000] "GET /js/worker.2460f36ba.js.map HTTP/1.1" 200 1787971 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:10 +0000] "GET /js/main.2460f36ba.js.map HTTP/1.1" 200 12499407 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:12 +0000] "GET /js/shared.2460f36ba.js.map HTTP/1.1" 200 17657781 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:12 +0000] "GET /js/shared.2460f36ba.js.map HTTP/1.1" 200 17657781 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:14 +0000] "POST /api/rpc/command/update-file HTTP/1.1" 200 264 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
--[06/Mar/2023:20:50:42 +0000] "POST /api/export HTTP/1.1" 500 188 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
10.233.68.15 - - [06/Mar/2023:20:51:54 +0000] "GET / HTTP/1.1" 200 1002988 "-" "curl/7.81.0"
```
```


### Backend Stack Trace

```console
Backend:

+ exec /opt/jdk/bin/java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dlog4j2.configurationFile=log4j2.xml -XX:-OmitStackTraceInFastThrow -jar penpot.jar -m app.main
2023-03-06 20:27:46,299 main INFO Registered Log4j as the java.util.logging.LogManager.
[2023-03-06 20:28:18.592] I app.metrics - action="initialize metrics"
[2023-03-06 20:28:19.095] I app.db - hint="initialize connection pool", name="main", uri="postgresql://postgres.penpot:5432/penpot", read-only=false, with-credentials=true, min-size=0, max-size=60
[2023-03-06 20:28:22.891] I app.redis - hint="initialize redis resources", uri="redis://redis.penpot:6379/0", io-threads=3, worker-threads=3, connect?=nil
[2023-03-06 20:28:24.397] I app.msgbus - hint="initialize msgbus", buffer-size=128
[2023-03-06 20:28:28.592] I app.setup.builtin-templates - hint="loading template files", total=9
[2023-03-06 20:28:33.191] I app.http - hint="starting http server", port=6060, host="0.0.0.0", name="http"
[2023-03-06 20:28:33.395] I io.undertow - starting server: Undertow - 2.3.0.Final
[2023-03-06 20:28:33.399] I org.xnio - XNIO version 3.8.8.Final
[2023-03-06 20:28:33.491] I org.xnio.nio - XNIO NIO Implementation Version 3.8.8.Final
[2023-03-06 20:28:33.505] I org.jboss.threads - JBoss Threads version 3.5.0.Final
[2023-03-06 20:28:33.794] I app.loggers.zmq - hint="receiver started"
[2023-03-06 20:28:33.889] I app.loggers.database - hint="initializing database error persistence"
[2023-03-06 20:28:33.894] I app.storage.tmp - hint="started tmp file cleaner"
[2023-03-06 20:28:34.190] I app.worker - hint="registry initialized", tasks=13
[2023-03-06 20:28:34.304] I app.worker - hint="cron: started", tasks=8
[2023-03-06 20:28:34.789] I app.worker - hint="dispatcher: started"
[2023-03-06 20:28:34.890] I app.worker - hint="monitor: started", name="default"
[2023-03-06 20:28:34.989] I app.worker - hint="worker: started", worker-id=0, queue="default"
[2023-03-06 20:28:35.088] I app.worker - hint="worker: started", worker-id=0, queue="webhooks"
[2023-03-06 20:28:35.090] I app.main - hint="welcome to penpot", flags="login-with-password,backend-api-doc,login,backend-worker,registration,backend-api-docs", worker?=true, version="1.17.1-9406-g2460f36ba"
[2023-03-06 21:00:00.017] I app.tasks.file-xlog-gc - hint="task finished", min-age="72h", total=0

```
Exporter:
```
INF [app.core] msg="initializing", public-uri="http://frontend.penpot:80", version="1.17.1-9406-g2460f36ba"
INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
INF [app.http] hint="welcome to penpot", module="exporter", version="1.17.1-9406-g2460f36ba"
INF [app.http] hint="starting http server", port=6061
INF [app.redis] hint="redis connection established", uri="redis://redis.penpot:6379/0"
WRN [app.redis] hint="connection closed"
INF [app.redis] hint="redis connection established", uri="redis://redis.penpot:6379/0"
DBG [app.handlers] hint="process-request", cmd=:export-shapes
SEV [app.handlers.export-shapes] hint="unexpected error on export multiple"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
SEV [app.handlers] hint="unexpected internal error"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
INF [app.browser] origin="factory", action="create", browser-id=2
INF [app.browser] origin="factory", action="destroy", browser-id=2
DBG [app.handlers] hint="process-request", cmd=:export-shapes
SEV [app.handlers.export-shapes] hint="unexpected error on export multiple"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
SEV [app.handlers] hint="unexpected internal error"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
INF [app.browser] origin="factory", action="create", browser-id=3
INF [app.browser] origin="factory", action="destroy", browser-id=3
DBG [app.handlers] hint="process-request", cmd=:export-shapes
SEV [app.handlers.export-shapes] hint="unexpected error on export multiple"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
SEV [app.handlers] hint="unexpected internal error"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
INF [app.browser] origin="factory", action="create", browser-id=4
INF [app.browser] origin="factory", action="destroy", browser-id=4
DBG [app.handlers] hint="process-request", cmd=:export-shapes
SEV [app.handlers.export-shapes] hint="unexpected error on export multiple"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
SEV [app.handlers] hint="unexpected internal error"
cause data: {:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
    at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25519:14)
    at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25554:10)
    at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:56085:29)
    at Function.$G__21561__1$$ [as cljs$core$IFn$_invoke$arity$1] (/opt/penpot/exporter/app.js:13346:112)
    at /opt/penpot/exporter/app.js:55035:56
INF [app.browser] origin="factory", action="create", browser-id=5
INF [app.browser] origin="factory", action="destroy", browser-id=5
```
```


### Additional context

_No response_

**Comment by niwinz** [comment]
I'm pretty sure this is something configuration/environment related but I need to research why it is happening. Nothing evident on logs

**Comment by elizabethejs** [comment]
Me ocurrió lo mismo, saben por que da el error?

**Comment by elizabethejs** [comment]
Me he revisado todos los post relacionados con este tema y ninguno me ha ayudado, por favor, me podéis ayudar?
Con la versión 1.19.2 de penpot me sigue ocurriendo este error en el exporter al realizar una exportación de múltiples elementos.

INF [app.core] msg="initializing", public-uri="prueba-penpot.apps.paas-des.junta-andalucia.es", version="1.19.2-10670-gcc5b1c950"
INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
INF [app.http] hint="welcome to penpot", module="exporter", version="1.19.2-10670-gcc5b1c950"
INF [app.http] hint="starting http server", port=6061
INF [app.redis] hint="redis connection established", uri="redis://svc-penpot-redis/0"
WRN [app.redis] hint="connection closed"
INF [app.redis] hint="redis connection established", uri="redis://svc-penpot-redis/0"
DBG [app.handlers] hint="process-request", cmd=:export-shapes
ERR [app.handlers.export-shapes] hint="unexpected error on multiple exportation"
Data:
{:type :internal, :code :timeout, :hint "ResourceRequest timed out"}
Error: ResourceRequest timed out
at new cljs.core.ExceptionInfo (/opt/penpot/exporter/app.js:25520:14)
at cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:25555:10)
at app.browser.translate_browser_errors (/opt/penpot/exporter/app.js:69735:29)
at /opt/penpot/exporter/app.js:69053:134
at Object.reject (/opt/penpot/exporter/app.js:68568:107)
at $jscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:67614:167)
at $jscomp$scope$84173391$26$transition (/opt/penpot/exporter/app.js:67593:110)
at $jscomp$scope$84173391$13$PromiseImpl.reject (/opt/penpot/exporter/app.js:67691:82)
at Object.complete (/opt/penpot/exporter/app.js:67627:28)
at $jscomp$scope$84173391$25$resolveTask (/opt/penpot/exporter/app.js:67596:22)
