### ISSUE TITLE
bug: docker compose environment "PENPOT_SMTP_SSL=true" not working

### ISSUE THREAD

**Issue by GeekSquirrel** [uxbox/uxbox#3213]
### Steps To Reproduce

modify the official compose file to use smtp server

### Expected behavior

smtp works

### Actual behavior

Sending Email timeout.
When using flag enable-smtp-debug, the log showed 'trying to connect to host "smtp.qq.com", port 465, isSSL false' even if I set "PENPOT_SMTP_SSL" to true.

### Backend Stack Trace

```console
penpot-penpot-backend-1   | DEBUG: Jakarta Mail version 2.0.1
penpot-penpot-backend-1   | DEBUG: successfully loaded resource: /META-INF/javamail.default.providers
penpot-penpot-backend-1   | DEBUG: Tables of loaded providers
penpot-penpot-backend-1   | DEBUG: Providers Listed By Class Name: {com.sun.mail.smtp.SMTPTransport=jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], com.sun.mail.imap.IMAPSSLStore=jakarta.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], com.sun.mail.pop3.POP3Store=jakarta.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], com.sun.mail.smtp.SMTPSSLTransport=jakarta.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], com.sun.mail.imap.IMAPStore=jakarta.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], com.sun.mail.pop3.POP3SSLStore=jakarta.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
penpot-penpot-backend-1   | DEBUG: Providers Listed By Protocol: {imap=jakarta.mail.Provider[STORE,imap,com.sun.mail.imap.IMAPStore,Oracle], smtp=jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle], pop3=jakarta.mail.Provider[STORE,pop3,com.sun.mail.pop3.POP3Store,Oracle], imaps=jakarta.mail.Provider[STORE,imaps,com.sun.mail.imap.IMAPSSLStore,Oracle], smtps=jakarta.mail.Provider[TRANSPORT,smtps,com.sun.mail.smtp.SMTPSSLTransport,Oracle], pop3s=jakarta.mail.Provider[STORE,pop3s,com.sun.mail.pop3.POP3SSLStore,Oracle]}
penpot-penpot-backend-1   | DEBUG: successfully loaded resource: /META-INF/javamail.default.address.map
penpot-penpot-backend-1   | DEBUG: getProvider() returning jakarta.mail.Provider[TRANSPORT,smtp,com.sun.mail.smtp.SMTPTransport,Oracle]
penpot-penpot-backend-1   | DEBUG SMTP: useEhlo true, useAuth true
penpot-penpot-backend-1   | DEBUG SMTP: trying to connect to host "smtp.qq.com", port 465, isSSL false
penpot-penpot-backend-1   | DEBUG SMTP: exception reading response, THROW:
penpot-penpot-backend-1   | java.net.SocketTimeoutException: Read timed out
penpot-penpot-backend-1   | 	at java.base/sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:280)
penpot-penpot-backend-1   | 	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:306)
penpot-penpot-backend-1   | 	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347)
penpot-penpot-backend-1   | 	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800)
penpot-penpot-backend-1   | 	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:966)
penpot-penpot-backend-1   | 	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102)
penpot-penpot-backend-1   | 	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
penpot-penpot-backend-1   | 	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:263)
penpot-penpot-backend-1   | 	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100)
penpot-penpot-backend-1   | 	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456)
penpot-penpot-backend-1   | 	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172)
penpot-penpot-backend-1   | 	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
penpot-penpot-backend-1   | 	at jakarta.mail.Service.connect(Service.java:342)
penpot-penpot-backend-1   | 	at jakarta.mail.Service.connect(Service.java:222)
penpot-penpot-backend-1   | 	at jakarta.mail.Service.connect(Service.java:243)
penpot-penpot-backend-1   | 	at app.email$eval31769$fn__31770$fn__31771$fn__31772.invoke(email.clj:307)
penpot-penpot-backend-1   | 	at app.email$eval31769$fn__31770$fn__31771.invoke(email.clj:306)
penpot-penpot-backend-1   | 	at app.email$eval31793$fn__31795$fn__31798.invoke(email.clj:326)
penpot-penpot-backend-1   | 	at app.worker$wrap_task_handler$fn__10919.invoke(worker.clj:83)
penpot-penpot-backend-1   | 	at app.worker$run_worker_loop_BANG_$handle_task__11563.invoke(worker.clj:394)
penpot-penpot-backend-1   | 	at app.worker$run_worker_loop_BANG_$run_task__11613.invoke(worker.clj:454)
penpot-penpot-backend-1   | 	at app.worker$run_worker_loop_BANG_$run_task_loop__11699.invoke(worker.clj:468)
penpot-penpot-backend-1   | 	at app.worker$run_worker_loop_BANG_.invokeStatic(worker.clj:485)
penpot-penpot-backend-1   | 	at app.worker$run_worker_loop_BANG_.invoke(worker.clj:344)
penpot-penpot-backend-1   | 	at app.worker$start_worker_BANG_$runnable_11415__11416.invoke(worker.clj:327)
penpot-penpot-backend-1   | 	at clojure.lang.AFn.run(AFn.java:22)
penpot-penpot-backend-1   | 	at java.base/java.lang.Thread.run(Thread.java:833)
penpot-penpot-backend-1   | [2023-05-15 10:03:45.444] E app.worker - hint="worker: unhandled exception on task"
penpot-penpot-backend-1   | SUMMARY:
penpot-penpot-backend-1   |  →  jakarta.mail.MessagingException: Exception reading response (SMTPTransport.java:2476)
penpot-penpot-backend-1   |  →  java.net.SocketTimeoutException: Read timed out (NioSocketImpl.java:280)
penpot-penpot-backend-1   | DETAIL:
penpot-penpot-backend-1   |  →  jakarta.mail.MessagingException: Exception reading response (SMTPTransport.java:2476)
penpot-penpot-backend-1   |     at: com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2476)
penpot-penpot-backend-1   |         com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172)
penpot-penpot-backend-1   |         com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:342)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:222)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:243)
penpot-penpot-backend-1   |         app.email$eval31769$fn__31770$fn__31771$fn__31772.invoke(email.clj:307)
penpot-penpot-backend-1   |         app.email$eval31769$fn__31770$fn__31771.invoke(email.clj:306)
penpot-penpot-backend-1   |         app.email$eval31793$fn__31795$fn__31798.invoke(email.clj:326)
penpot-penpot-backend-1   |         app.worker$wrap_task_handler$fn__10919.invoke(worker.clj:83)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$handle_task__11563.invoke(worker.clj:394)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$run_task__11613.invoke(worker.clj:454)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$run_task_loop__11699.invoke(worker.clj:468)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_.invokeStatic(worker.clj:485)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_.invoke(worker.clj:344)
penpot-penpot-backend-1   |         app.worker$start_worker_BANG_$runnable_11415__11416.invoke(worker.clj:327)
penpot-penpot-backend-1   |         clojure.lang.AFn.run(AFn.java:22)
penpot-penpot-backend-1   |         java.lang.Thread.run(Thread.java:833)
penpot-penpot-backend-1   |
penpot-penpot-backend-1   |  →  java.net.SocketTimeoutException: Read timed out (NioSocketImpl.java:280)
penpot-penpot-backend-1   |     at: sun.nio.ch.NioSocketImpl.timedRead(NioSocketImpl.java:280)
penpot-penpot-backend-1   |         sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:306)
penpot-penpot-backend-1   |         sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:347)
penpot-penpot-backend-1   |         sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:800)
penpot-penpot-backend-1   |         java.net.Socket$SocketInputStream.read(Socket.java:966)
penpot-penpot-backend-1   |         com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:102)
penpot-penpot-backend-1   |         java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
penpot-penpot-backend-1   |         java.io.BufferedInputStream.read(BufferedInputStream.java:263)
penpot-penpot-backend-1   |         com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:100)
penpot-penpot-backend-1   |         com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2456)
penpot-penpot-backend-1   |         com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2172)
penpot-penpot-backend-1   |         com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:342)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:222)
penpot-penpot-backend-1   |         jakarta.mail.Service.connect(Service.java:243)
penpot-penpot-backend-1   |         app.email$eval31769$fn__31770$fn__31771$fn__31772.invoke(email.clj:307)
penpot-penpot-backend-1   |         app.email$eval31769$fn__31770$fn__31771.invoke(email.clj:306)
penpot-penpot-backend-1   |         app.email$eval31793$fn__31795$fn__31798.invoke(email.clj:326)
penpot-penpot-backend-1   |         app.worker$wrap_task_handler$fn__10919.invoke(worker.clj:83)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$handle_task__11563.invoke(worker.clj:394)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$run_task__11613.invoke(worker.clj:454)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_$run_task_loop__11699.invoke(worker.clj:468)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_.invokeStatic(worker.clj:485)
penpot-penpot-backend-1   |         app.worker$run_worker_loop_BANG_.invoke(worker.clj:344)
penpot-penpot-backend-1   |         app.worker$start_worker_BANG_$runnable_11415__11416.invoke(worker.clj:327)
penpot-penpot-backend-1   |         clojure.lang.AFn.run(AFn.java:22)
penpot-penpot-backend-1   |         java.lang.Thread.run(Thread.java:833)
penpot-penpot-backend-1   |
```

**Comment by niwinz** [comment]
I will look on it, thanks!
