### ISSUE TITLE
bug: referential-integrity ("error on validating file referential integrity") / nested-copy-not-allowed ("Nested copy component only allowed inside other component")

### ISSUE THREAD

**Issue by garrett** [uxbox/uxbox#4379]
### Steps To Reproduce

I've attached a file that's based on a pruned-down version of a file I was working on. 

1. Download [error_ nesting copy not allowed.zip](https://github.com/penpot/penpot/files/14907386/error_.nesting.copy.not.allowed.zip)
2. Extract the zip file
3. Import into Penpot
4. Try to move the grid-based "table" into the bottom modal dialog so that it looks similar to the topmost modal dialog

### Expected behavior

Penpot should not crash. Ideally, I'd be able to nest any objects.

(Ideally, if it hit an error like this, it'd be nice to get a modal with an error message and to be able to ignore the issue and keep working on the file.)

### Actual behavior

Crash!

### Screenshots or video

The document looks like this:

![image](https://github.com/penpot/penpot/assets/10246/6126f492-9b81-4792-9bfc-dd586d3420dc)

Move the bottom board (that looks like a table) into the bottom dialog that has a board that's selected (with a purple outline). It looks like it succeeds (which would look similar to the topmost dialog), but then crashes with the included crash report.

### Desktop (please complete the following information)

- Fedora Linux 40 beta, both with Chrome and Firefox

### Smartphone (please complete the following information)

- Android, Google Pixel 6 Pro

### Environment (please complete the following information)

- design.penpot.app

### Frontend Stack Trace

```console
Hint:    error on validating file referential integrity
Prof ID: 0dc6c770-6542-11eb-a7f8-eb0147e048f5
Team ID: 8ad824c0-6542-11eb-a7f8-eb0147e048f5
File ID: 7778d259-7b64-808e-8004-2ad32c44aca7

Data:
{:type :validation,
 :code :referential-integrity,
 :hint "error on validating file referential integrity",
 :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
 :details
 [{:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66ca",
                      :name "Form / Check / check, checked",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 594.9999999999991,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66ca",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d0",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 542.9999999999991,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d0",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d5",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 490.99999999999903,
                      :width 443.00000000000045,
                      :height 35.99999999999983,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d5",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66da",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 422.9999999999989,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66da",
   :args nil}]}

Trace:
Error: http error
    at new PENPOT.Dh (https://design.penpot.app/js/shared.8093555ac.js:3468:33)
    at PENPOT.Eh (https://design.penpot.app/js/shared.8093555ac.js:3468:355)
    at PENPOT.Fh (https://design.penpot.app/js/shared.8093555ac.js:3468:308)
    at PENPOT.Lx (https://design.penpot.app/js/shared.8093555ac.js:4409:110)
    at https://design.penpot.app/js/shared.8093555ac.js:4383:236
    at u (https://design.penpot.app/js/shared.8093555ac.js:243:276)
    at P.r [as _nextOverride] (https://design.penpot.app/js/shared.8093555ac.js:243:218)
    at P.d [as _next] (https://design.penpot.app/js/shared.8093555ac.js:150:99)
    at P.next (https://design.penpot.app/js/shared.8093555ac.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.8093555ac.js:221:222)
    at P.d [as _next] (https://design.penpot.app/js/shared.8093555ac.js:150:99)
    at P.next (https://design.penpot.app/js/shared.8093555ac.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.8093555ac.js:243:350)
    at P.d [as _next] (https://design.penpot.app/js/shared.8093555ac.js:150:99)
    at P.next (https://design.penpot.app/js/shared.8093555ac.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.8093555ac.js:221:222)
    at P.d [as _next] (https://design.penpot.app/js/shared.8093555ac.js:150:99)
    at P.next (https://design.penpot.app/js/shared.8093555ac.js:158:429)
    at https://design.penpot.app/js/shared.8093555ac.js:151:383

Last events:
[":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.transforms/move-shapes-to-frame"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.collapse/expand-collapse"
 ":app.main.data.workspace.transforms/move-shapes-to-frame"
 ":app.main.data.workspace.transforms/finish-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.texts/commit-position-data"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace/set-gap-selected"
 ":app.main.data.workspace/set-paddings-selected"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace.persistence/persist-changes"]
```

**Comment by madalenapmelo-kp** [comment]
Hi @garrett,

Thank you for reporting this! We just released a fix that should address this issue, could you clear your browser cache and let me know if the issue persists?

**Comment by garrett** [comment]
Thanks for the quick reply!

Unfortunately, I just did a shift-reload (ctrl-shift-r) and I'm still seeing the bug here. I even tried moving the grid "table" around a bit and waiting for the save before moving it into the dialog. It consistently crashes for me, in both Firefox and Chrome.

Here's the error report from the latest attempt (it basically looks the same to me):

```
Hint:    error on validating file referential integrity
Prof ID: 0dc6c770-6542-11eb-a7f8-eb0147e048f5
Team ID: 8ad824c0-6542-11eb-a7f8-eb0147e048f5
File ID: 7778d259-7b64-808e-8004-2ad32c44aca7

Data:
{:type :validation,
 :code :referential-integrity,
 :hint "error on validating file referential integrity",
 :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
 :details
 [{:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66ca",
                      :name "Form / Check / check, checked",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 594.9999999999992,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66ca",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d0",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 542.999999999999,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d0",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d5",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 490.9999999999989,
                      :width 443.00000000000045,
                      :height 35.99999999999994,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66d5",
   :args nil}
  {:code :nested-copy-not-allowed,
   :hint "Nested copy component only allowed inside other component",
   :shape
   ##object[Function]{:id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66da",
                      :name "Form / Select / Select",
                      :type :frame,
                      :x 3411.0000000000005,
                      :y 422.9999999999989,
                      :width 443.00000000000045,
                      :height 36,
                      :rotation 0,
                      :selrect ##object[Function]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "7778d259-7b64-808e-8004-2ad32c44aca7",
   :page-id #uuid "d8ac23cd-47df-8004-8002-0e207f539504",
   :shape-id #uuid "b3e7e9c6-0f46-80d2-8004-2ad190ed66da",
   :args nil}]}

Trace:
Error: http error
    at new PENPOT.Dh (https://design.penpot.app/js/shared.c5109a1cd.js:3468:33)
    at PENPOT.Eh (https://design.penpot.app/js/shared.c5109a1cd.js:3468:355)
    at PENPOT.Fh (https://design.penpot.app/js/shared.c5109a1cd.js:3468:308)
    at PENPOT.Lx (https://design.penpot.app/js/shared.c5109a1cd.js:4409:110)
    at https://design.penpot.app/js/shared.c5109a1cd.js:4383:236
    at u (https://design.penpot.app/js/shared.c5109a1cd.js:243:276)
    at P.r [as _nextOverride] (https://design.penpot.app/js/shared.c5109a1cd.js:243:218)
    at P.d [as _next] (https://design.penpot.app/js/shared.c5109a1cd.js:150:99)
    at P.next (https://design.penpot.app/js/shared.c5109a1cd.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.c5109a1cd.js:221:222)
    at P.d [as _next] (https://design.penpot.app/js/shared.c5109a1cd.js:150:99)
    at P.next (https://design.penpot.app/js/shared.c5109a1cd.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.c5109a1cd.js:243:350)
    at P.d [as _next] (https://design.penpot.app/js/shared.c5109a1cd.js:150:99)
    at P.next (https://design.penpot.app/js/shared.c5109a1cd.js:158:429)
    at P.next [as _nextOverride] (https://design.penpot.app/js/shared.c5109a1cd.js:221:222)
    at P.d [as _next] (https://design.penpot.app/js/shared.c5109a1cd.js:150:99)
    at P.next (https://design.penpot.app/js/shared.c5109a1cd.js:158:429)
    at https://design.penpot.app/js/shared.c5109a1cd.js:151:383

Last events:
[":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.modifiers/set-modifiers"
 ":app.main.data.workspace.transforms/set-ghost-displacement"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.transforms/move-shapes-to-frame"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.collapse/expand-collapse"
 ":app.main.data.workspace.transforms/move-shapes-to-frame"
 ":app.main.data.workspace.transforms/finish-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.texts/commit-position-data"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace/set-gap-selected"
 ":app.main.data.workspace/set-paddings-selected"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.workspace.grid-layout.editor/stop-grid-layout-editing"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.persistence/persist-changes"]
```

**Comment by madalenapmelo-kp** [comment]
@garrett we'll continue to look into this. 

In the meantime, as a workaround, it seems that moving the layers from the layers menu instead of the viewport does not generate the error, could you confirm if that's the case for you as well?

**Comment by hirunatan** [comment]
@garrett we have implemented a fix that will avoid the crash. It will be applied in design.penpot.app in the next update.

However, there is an important change.

One of the main things that are different in components in Penpot 2.0 is that, from now on, you cannot change the structure of component copies. This means that if you delete a layer in a copy, it only becomes hidden. And you cannot add layers into a copy. In your case, for example, you won't be able to move the form block into the dialog, either in the workspace or in the layers menu.

We have now a different mechanism for this: component swap. You can see what is this in the help center:

https://help.penpot.app/user-guide/components/#component-swap

To use this, you need to reorganize your file a bit. Any part of a component that may be replaced now needs to be also a component, and the replacing parts too. And you can swap them in the copies.

This is a more controlled and descriptive way of customizing components, we hope it's useful for you.

**Comment by hirunatan** [comment]
@garrett the fix has been deployed. If you try the operation now, you'll find that there is no error, but the moved board is not put inside the component.

To be able to do it, you need to make the form board a component, and also the placeholder in the modal component. With this you will be able to do the swap.
