### ISSUE TITLE
bug: Error when trying to export

### ISSUE THREAD

**Issue by hades200082** [uxbox/uxbox#4432]
### Steps To Reproduce

1. Self host Penpot using docker compose
2. Create a board with stuff on it
3. Try to export the board as a PNG

### Expected behavior

PNG is exported/downloaded

### Actual behavior

Error:
![image](https://github.com/penpot/penpot/assets/1023581/5a007877-73e3-414a-ad1f-f0084ffb8111)

### Desktop (please complete the following information)

Windows 11
Edge browser

### Environment (please complete the following information)

- OS: Ubuntu 22.04
- Docker-compose (hosted in Coolify)

```yaml
version: '3.5'
networks:
  penpot: null
volumes:
  penpot_postgres_v15: null
  penpot_assets: null
services:
  penpot-frontend:
    image: 'penpotapp/frontend:latest'
    restart: always
    ports:
      - '9001:80'
    volumes:
      - 'penpot_assets:/opt/data/assets'
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    environment:
      - SERVICE_FQDN_PENPOT-FRONTEND
      - 'PENPOT_FLAGS=${PENPOT_FRONTEND_FLAGS}'
  penpot-backend:
    image: 'penpotapp/backend:latest'
    restart: always
    volumes:
      - 'penpot_assets:/opt/data/assets'
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - penpot
    environment:
      - SERVICE_FQDN_PENPOT-BACKEND
      - 'PENPOT_FLAGS=${PENPOT_BACKEND_FLAGS}'
      - 'PENPOT_SECRET_KEY=${PENPOT_SECRET_KEY}'
      - 'PENPOT_PUBLIC_URI=${SERVICE_FQDN_PENPOT-FRONTEND}'
      - 'PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot'
      - 'PENPOT_DATABASE_USERNAME=${SERVICE_USER_POSTGRES}'
      - 'PENPOT_DATABASE_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
      - 'PENPOT_REDIS_URI=redis://penpot-redis/0'
      - PENPOT_ASSETS_STORAGE_BACKEND=assets-fs
      - PENPOT_STORAGE_ASSETS_FS_DIRECTORY=/opt/data/assets
      - 'PENPOT_TELEMETRY_ENABLED=${PENPOT_TELEMETRY_ENABLED}'
      - 'PENPOT_SMTP_DEFAULT_FROM=${PENPOT_SMTP_DEFAULT_FROM}'
      - 'PENPOT_SMTP_DEFAULT_REPLY_TO=${PENPOT_SMTP_DEFAULT_REPLY_TO}'
      - 'PENPOT_SMTP_HOST=${PENPOT_SMTP_HOST}'
      - 'PENPOT_SMTP_PORT=${PENPOT_SMTP_PORT}'
      - 'PENPOT_SMTP_USERNAME=${PENPOT_SMTP_USERNAME}'
      - 'PENPOT_SMTP_PASSWORD=${PENPOT_SMTP_PASSWORD}'
      - 'PENPOT_SMTP_TLS=${PENPOT_SMTP_TLS}'
      - 'PENPOT_SMTP_SSL=${PENPOT_SMTP_SSL}'
  penpot-exporter:
    image: 'penpotapp/exporter:latest'
    restart: always
    networks:
      - penpot
    environment:
      - SERVICE_FQDN_PENPOT-EXPORTER
      - 'PENPOT_PUBLIC_URI=${SERVICE_FQDN_PENPOT-FRONTEND}'
      - 'PENPOT_REDIS_URI=redis://penpot-redis/0'
  penpot-postgres:
    image: 'postgres:15'
    restart: always
    stop_signal: SIGINT
    volumes:
      - 'penpot_postgres_v15:/var/lib/postgresql/data'
    networks:
      - penpot
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_DB=penpot
      - 'POSTGRES_USER=${SERVICE_USER_POSTGRES}'
      - 'POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}'
  penpot-redis:
    image: 'redis:7'
    restart: always
    networks:
      - penpot
```

### Backend Stack Trace

```console
Hint:    Cookie should have a url or a domain/path pair
Prof ID: 3330eb64-eb6b-8109-8004-036877b83005
Team ID: 3330eb64-eb6b-8109-8004-0368f245f3c2

Data:
{:type :server-error, :hint "Cookie should have a url or a domain/path pair"}

Trace:
Error: http error
    at new PENPOT.Dh (https://penpot.REDACTED.org/js/shared.41cdd2453.js:3468:33)
    at PENPOT.Eh (https://penpot.REDACTED.org/js/shared.41cdd2453.js:3468:355)
    at PENPOT.Fh (https://penpot.REDACTED.org/js/shared.41cdd2453.js:3468:308)
    at PENPOT.Lx (https://penpot.REDACTED.org/js/shared.41cdd2453.js:4409:110)
    at https://penpot.REDACTED.org/js/shared.41cdd2453.js:4383:236
    at u (https://penpot.REDACTED.org/js/shared.41cdd2453.js:243:276)
    at P.r [as _nextOverride] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:243:218)
    at P.d [as _next] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:150:99)
    at P.next (https://penpot.REDACTED.org/js/shared.41cdd2453.js:158:429)
    at P.next [as _nextOverride] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:221:222)
    at P.d [as _next] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:150:99)
    at P.next (https://penpot.REDACTED.org/js/shared.41cdd2453.js:158:429)
    at P.next [as _nextOverride] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:243:350)
    at P.d [as _next] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:150:99)
    at P.next (https://penpot.REDACTED.org/js/shared.41cdd2453.js:158:429)
    at P.next [as _nextOverride] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:221:222)
    at P.d [as _next] (https://penpot.REDACTED.org/js/shared.41cdd2453.js:150:99)
    at P.next (https://penpot.REDACTED.org/js/shared.41cdd2453.js:158:429)
    at https://penpot.REDACTED.org/js/shared.41cdd2453.js:151:383

Last events:
[":app.main.data.workspace/set-gap-selected"
 ":app.main.data.workspace/set-paddings-selected"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace.zoom/set-zoom"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/commit-changes"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.workspace.persistence/persist-changes"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace.thumbnails/update"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.changes/update-indices"
 ":app.main.data.workspace.persistence/shapes-changes-persisted"
 ":app.main.data.workspace.persistence/shapes-changes-persisted-finished"
 ":app.main.data.workspace.changes/send-update-indices"
 ":app.main.data.workspace.thumbnails/request-thumbnail"
 ":app.main.data.exports/request-simple-export"
 ":app.main.data.exports/clear-export-state"]
```

### Additional context

Application logs from Exporter service:

```
2024-04-13T17:23:37.462209556Z INF [app.util.shell] hint="tmptdir setup", path="/tmp/penpot-exporter"
2024-04-13T17:23:37.464573942Z INF [app.core] msg="initializing", public-uri="FRONTEND", version="2.0.0-13149-g41cdd2453"
2024-04-13T17:23:37.475717478Z INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
2024-04-13T17:23:37.481404305Z INF [app.http] hint="welcome to penpot", module="exporter", flags=#{}, version="2.0.0-13149-g41cdd2453"
2024-04-13T17:23:37.482587086Z INF [app.http] hint="starting http server", port=6061
2024-04-13T17:23:37.725506583Z INF [app.redis] hint="redis connection established", uri="redis://penpot-redis/0"
2024-04-13T18:09:03.583195500Z DBG [app.handlers] hint="process-request", cmd=:export-shapes
2024-04-13T18:09:04.890876271Z INF [app.browser] origin="factory", action="create", browser-id=2
2024-04-13T18:09:04.894019476Z INF [app.browser] origin="factory", action="validate", browser-id=2, obj=#object[Browser [object Object]]
2024-04-13T18:09:04.908896100Z INF [app.browser] origin="factory", action="destroy", browser-id=2
2024-04-13T18:09:04.910557218Z ERR [app.handlers.export-shapes] hint="unexpected error on export multiple"
2024-04-13T18:09:04.911309626Z   
2024-04-13T18:09:04.918595642Z ERR [app.handlers] hint="unexpected internal error"
2024-04-13T18:09:04.918730534Z   
2024-04-13T18:09:27.373600123Z DBG [app.handlers] hint="process-request", cmd=:export-shapes
2024-04-13T18:09:27.609615982Z INF [app.browser] origin="factory", action="create", browser-id=3
2024-04-13T18:09:27.610642191Z INF [app.browser] origin="factory", action="validate", browser-id=3, obj=#object[Browser [object Object]]
2024-04-13T18:09:27.619194714Z INF [app.browser] origin="factory", action="destroy", browser-id=3
2024-04-13T18:09:27.620037203Z ERR [app.handlers.export-shapes] hint="unexpected error on export multiple"
2024-04-13T18:09:27.620104961Z   
2024-04-13T18:09:27.621706445Z ERR [app.handlers] hint="unexpected internal error"
2024-04-13T18:09:27.621729032Z   
2024-04-13T18:13:04.531671893Z DBG [app.handlers] hint="process-request", cmd=:export-shapes
2024-04-13T18:13:04.747737034Z INF [app.browser] origin="factory", action="create", browser-id=4
2024-04-13T18:13:04.749835131Z INF [app.browser] origin="factory", action="validate", browser-id=4, obj=#object[Browser [object Object]]
2024-04-13T18:13:04.757215226Z INF [app.browser] origin="factory", action="destroy", browser-id=4
2024-04-13T18:13:04.757822474Z ERR [app.handlers.export-shapes] hint="unexpected error on export multiple"
2024-04-13T18:13:04.757931350Z   
2024-04-13T18:13:04.759263332Z ERR [app.handlers] hint="unexpected internal error"
2024-04-13T18:13:04.759318643Z
```

**Comment by hades200082** [comment]
I've fixed this myself. 

If anyone else has this issue, in the docker-compose under the exporter service I needed to specify the front-end URL environment variable as the internal URL within the docker network, not the public URL.
