### ISSUE TITLE
bug:  Cannot read properties of undefined (reading 'writeText')

### ISSUE THREAD

**Issue by greenbrainsecke** [uxbox/uxbox#4478]
### Steps To Reproduce

Select Board, Go to Specification, then Code and copy Code to clipboard

### Expected behavior

That the code is copied to the clipboard

### Actual behavior

Hello, I have the following problem: I'm creating something in Penpot 2 and would like to copy the CSS or HTML code to the clipboard and I get an error screen and the following error message:

### Screenshots or video

![Screenshot 2024-04-21 013809](https://github.com/penpot/penpot/assets/48941397/53f44688-5513-4917-b724-6752e1316efa)

### Environment (please complete the following information)

Hint:    Cannot read properties of undefined (reading 'writeText')
Prof ID: 681277dd-509d-810d-8004-2d6683e807b4
Team ID: 681277dd-509d-810d-8004-2d668445e021

Data:
{:hint "Cannot read properties of undefined (reading 'writeText')"}

Trace:
TypeError: Cannot read properties of undefined (reading 'writeText')
    at PENPOT.hO (http://192.168.1.52:9001/js/main.33bdf5e83.js:849:235)
    at http://192.168.1.52:9001/js/main.33bdf5e83.js:2453:426
    at Object.ob (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1037:218)
    at Bb (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1037:311)
    at Qb (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1037:370)
    at ud (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1064:469)
    at Xd (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1065:420)
    at http://192.168.1.52:9001/js/shared.33bdf5e83.js:1076:57
    at Hi (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1198:44)
    at Sa (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1036:21)
    at Kc (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1068:190)
    at Tc (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1050:253)
    at Dc (http://192.168.1.52:9001/js/shared.33bdf5e83.js:1050:29)

Last events:
[":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.events/event"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.messages/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.layout/ensure-layout"
 ":app.main.data.workspace/initialize-layout"
 ":app.main.data.messages/hide"
 ":app.main.data.comments/retrieve-comment-threads"
 ":app.main.data.workspace.persistence/initialize-persistence"
 ":app.main.data.workspace/fetch-bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle"
 ":app.main.data.workspace/initialize-file"
 ":app.main.features/initialize"
 ":app.main.data.users/set-current-team"
 ":app.main.data.workspace/bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle-stage-2"
 ":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.workspace.fix-bool-contents/fix-bool-contents"
 ":app.main.data.workspace.changes/update-shapes"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.layout/set-options-mode"
 ":app.main.data.workspace.layout/remove-layout-flag"
 ":app.main.data.workspace/set-workspace-read-only"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"]

### Additional context

It doesn't work in Chrome, Edge or FireFox

**Comment by madalenapmelo-kp** [comment]
Hi @greenbrainsecke,

Thanks for reporting this! I haven't been able to reproduce this behavior, could you send a screen recording or the .penpot file where you are experiencing this to support@penpot.app so that we can look into it?

**Comment by greenbrainsecke** [comment]
Hello PenPot Team, here is the video as requested
Greetings
Michael
https://drive.google.com/file/d/13iJHj_JvJGnrG6Lh3X7K6Ilb73_qGzg9/view?usp=sharing

Am Mo., 22. Apr. 2024 um 12:51 Uhr schrieb Madalena Melo
***@***.***>:

**Comment by madalenapmelo-kp** [comment]
@greenbrainsecke could you export the .penpot file where you are seeing this issue and send it to support@penpot.app?

**Comment by greenbrainsecke** [comment]
Thats in every PenPot File.
PenPot ist SelfHosted.

Am Mi., 24. Apr. 2024 um 11:36 Uhr schrieb Madalena Melo <
***@***.***>:

**Comment by pmwangyang** [comment]
saw this exception either.
while I'm using textbox, first input Chinese Fonts into the text box, or copy the textbox by "Ctrl + C",then the browser shows me the error.

**Comment by pmwangyang** [comment]
workspace.cljs:1653  clipboard blocked: TypeError: Cannot read properties of undefined (reading 'writeText')
    at PENPOT.hO (webapi.cljs:104:21)
    at core.cljs:267:7
    at P.next [as _nextOverride] (map.js:12:34)
    at P.d [as _next] (Observable.js:178:14)
    at P.next (Observable.js:123:18)
    at P.next [as _nextOverride] (map.js:12:29)
    at P.d [as _next] (Observable.js:178:14)
    at P.next (Observable.js:123:18)
    at P.next [as _nextOverride] (map.js:12:29)
    at P.d [as _next] (Observable.js:178:14)
    at P.next (Observable.js:123:18)
    at P.next [as _nextOverride] (map.js:12:29)
    at P.d [as _next] (Observable.js:178:14)
    at P.next (Observable.js:123:18)
    at h.subscribe.complete [as _completeOverride] (scanInternals.js:23:41)
    at P.c [as _complete] (Observable.js:197:14)
    at P.complete (Observable.js:141:18)
    at P.complete [as _completeOverride] (mergeInternals.js:14:25)
    at P.c [as _complete] (Observable.js:197:14)
    at P.complete (Observable.js:141:18)
    at ja._subscribe (Observable.js:448:20)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at l.mergeInternals (mergeInternals.js:58:12)
    at ja._subscribe (mergeMap.js:8:71)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at l.scanInternals (scanInternals.js:10:12)
    at ja._subscribe (reduce.js:9:71)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (map.js:9:16)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (map.js:9:16)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (map.js:9:16)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (map.js:9:16)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (catchError.js:11:27)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (ignoreElements.js:9:16)
    at ja._trySubscribe (Observable.js:275:25)
    at ja.subscribe (Observable.js:270:29)
    at ja._subscribe (catchError.js:11:27)

**Comment by pmwangyang** [comment]
> Hi @greenbrainsecke,
> 
> Thanks for reporting this! I haven't been able to reproduce this behavior, could you send a screen recording or the .penpot file where you are experiencing this to [support@penpot.app](mailto:support@penpot.app) so that we can look into it?

Dear developer, just sent you an email about this issue

**Comment by matroxok** [comment]
Hello, I have the same problem. After clicked copy code (html, css, svg) or after clicking copy colors etc. Problem is only in inspect mode. 

Host: docker - selfhost

**Comment by alexdoronin** [comment]
**UPDATE, Problem Solving:**

If you use an SSL certificate (meaning Penpot must run over HTTPS), this problem is solved! 
It seems to be related to the way Clipboard API works in browsers. Probably in unsecure environment (http) browsers restrict Clipboard operations.

---
I have absolutely the same error as @greenbrainsecke. It occurs when I press **any copy button** (copy parameters/code/link/etc). 

Example:
Inspect => Info => Copy Weight
View mode => Share => Get link => Copy link 
Code => copy HTML or SVG 

In Chrome dev console:

```
index.js:3265 TypeError: Cannot read properties of undefined (reading 'writeText')
  at PENPOT.EEb (webapi.cljs:104:21)
  at copy_button.cljs:37:15
  at Object.ob (react-dom.production.min.js:55:317)
  at Bb (react-dom.production.min.js:55:471)
  at Ob (react-dom.production.min.js:56:35)
  at ud (react-dom.production.min.js:106:68)
  at Xd (react-dom.production.min.js:107:380)
  at react-dom.production.min.js:118:104
  at Hi (react-dom.production.min.js:274:42)
  at Sa (react-dom.production.min.js:53:375)
  at Lc (react-dom.production.min.js:110:469)
  at Uc (react-dom.production.min.js:75:59)
  at Dc (react-dom.production.min.js:74:73)
(anonymous) @ index.js:3265

errors.cljs:47 Unhandled Error
errors.cljs:42 TypeError: Cannot read properties of undefined (reading 'writeText')
  at PENPOT.EEb (webapi.cljs:104:21)
  at copy_button.cljs:37:15
  at Object.ob (react-dom.production.min.js:55:317)
  at Bb (react-dom.production.min.js:55:471)
  at Ob (react-dom.production.min.js:56:35)
  at ud (react-dom.production.min.js:106:68)
  at Xd (react-dom.production.min.js:107:380)
  at react-dom.production.min.js:118:104
  at Hi (react-dom.production.min.js:274:42)
  at Sa (react-dom.production.min.js:53:375)
  at Lc (react-dom.production.min.js:110:469)
  at Uc (react-dom.production.min.js:75:59)
  at Dc (react-dom.production.min.js:74:73)
errors.cljs:25 {:hint "Cannot read properties of undefined (reading 'writeText')"}
```

It does not depend on the Penpot file, for example, I just have a rectangle (and nothing else), when copying any parameter (SVG code for example), this error will occur.

Penpot version: "2.1.2-13998-ga1c78683f"
Self-hosted: Nginx as reverse proxy + Docker
Mac OS, Chrome: 126.0.6478.127

The same error in other browsers:

Firefox:
TypeError: navigator.clipboard is undefined

Safari:
TypeError: undefined is not an object (evaluating 'navigator.clipboard.writeText')

**Comment by psiwray** [comment]
Same problem here, not using SSL certificates.

**Comment by yamila-moreno** [comment]
Hi there! as per the documentation, the clipboard does not work with HTTP, and it's mandatory to use HTTPS (also recommended for many other reasons).
You can check this: https://help.penpot.app/technical-guide/getting-started/docker/#configure-the-proxy-and-https

<img width="672" height="218" alt="Image" src="https://github.com/user-attachments/assets/0d23dc47-ba76-4981-b391-bbc8f2a38f21" />
