### ISSUE TITLE
bug: Unable to start  "api http error"

### ISSUE THREAD

**Issue by lingy-Mg** [uxbox/uxbox#4693]
### Steps To Reproduce

![image](https://github.com/penpot/penpot/assets/4111244/82e4da00-49ed-4c4c-812b-0fe00a6e06bf)

report.txt
```
Hint:    http error
Prof ID: --
Team ID: --

Data:
{:type :unexpected-error, :status 404, :data "(...)", :hint "http error"}

Trace:
Error: http error
    at new PENPOT.Dh (http://localhost:9001/js/shared.5eee1cdbf.js:3468:33)
    at PENPOT.Eh (http://localhost:9001/js/shared.5eee1cdbf.js:3468:355)
    at PENPOT.Fh (http://localhost:9001/js/shared.5eee1cdbf.js:3468:308)
    at PENPOT.Lx (http://localhost:9001/js/shared.5eee1cdbf.js:4409:147)
    at http://localhost:9001/js/shared.5eee1cdbf.js:4383:236
    at u (http://localhost:9001/js/shared.5eee1cdbf.js:243:276)
    at P.r [as _nextOverride] (http://localhost:9001/js/shared.5eee1cdbf.js:243:218)
    at P.d [as _next] (http://localhost:9001/js/shared.5eee1cdbf.js:150:99)
    at P.next (http://localhost:9001/js/shared.5eee1cdbf.js:158:429)
    at P.next [as _nextOverride] (http://localhost:9001/js/shared.5eee1cdbf.js:221:222)
    at P.d [as _next] (http://localhost:9001/js/shared.5eee1cdbf.js:150:99)
    at P.next (http://localhost:9001/js/shared.5eee1cdbf.js:158:429)
    at P.next [as _nextOverride] (http://localhost:9001/js/shared.5eee1cdbf.js:243:350)
    at P.d [as _next] (http://localhost:9001/js/shared.5eee1cdbf.js:150:99)
    at P.next (http://localhost:9001/js/shared.5eee1cdbf.js:158:429)
    at P.next [as _nextOverride] (http://localhost:9001/js/shared.5eee1cdbf.js:221:222)
    at P.d [as _next] (http://localhost:9001/js/shared.5eee1cdbf.js:150:99)
    at P.next (http://localhost:9001/js/shared.5eee1cdbf.js:158:429)
    at http://localhost:9001/js/shared.5eee1cdbf.js:151:383

Last events:
[":app.main.features/initialize"
 ":app.main.data.users/fetch-profile"
 ":app.main/initialize"
 ":app.main.data.events/event"]


```

Using Docker Desktop
docker compose -p penpot -f docker-compose.yaml up -d

### Expected behavior

Unable to start

### Actual behavior

Unable to start

### Desktop (please complete the following information)

win11

**Comment by lingy-Mg** [comment]
penpot-penpot-frontend-1  log
```
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET / HTTP/1.1" 200 560372 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /js/config.js?ts=1717671235396 HTTP/1.1" 200 110 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /fonts/WorkSans-Regular.woff2 HTTP/1.1" 200 71416 "http://localhost:9001/css/main.css?ts=1717671235406" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "HEAD / HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /api/rpc/command/get-profile HTTP/1.1" 404 5 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /rasterizer.html HTTP/1.1" 200 311 "http://localhost:9001/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /js/config.js?ts=1717671235396 HTTP/1.1" 200 110 "http://localhost:9001/rasterizer.html" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
2024-06-07 03:54:02 172.24.0.1 - - [06/Jun/2024:19:54:02 +0000] "GET /fonts/WorkSans-Medium.woff2 HTTP/1.1" 200 76068 "http://localhost:9001/css/main.css?ts=1717671235406" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0"
```

**Comment by lingy-Mg** [comment]
penpot-penpot-backend-1    log

```
2024-06-07 03:55:20 ++ cat classpath
2024-06-07 03:55:20 + exec /usr/lib/jvm/openjdk16/bin/java -classpath deps/app.jar:deps/clj-uuid-0.1.9.jar:deps/websocket-jetty-server-10.0.6.jar:deps/utils-2.17.40.jar:deps/jetty-webapp-10.0.6.jar:deps/reitit-ring-0.5.15.jar:deps/jetty-servlet-api-4.0.6.jar:deps/jackson-dataformat-smile-2.10.2.jar:deps/metrics-spi-2.17.40.jar:deps/simpleclient-0.9.0.jar:deps/im4java-1.4.0.jar:deps/next.jdbc-1.2.709.jar:deps/truss-1.6.0.jar:deps/jetty-servlet-10.0.6.jar:deps/netty-common-4.1.68.Final.jar:deps/promesa-6.0.1.jar:deps/eventstream-1.0.1.jar:deps/http2-common-10.0.6.jar:deps/auth-2.17.40.jar:deps/jackson-databind-2.12.3.jar:deps/jakarta.mail-2.0.1.jar:deps/asm-9.2.jar:deps/scrypt-1.2.0.jar:deps/clojure-1.10.3.jar:deps/checker-qual-3.5.0.jar:deps/jetty-xml-10.0.6.jar:deps/core.memoize-1.0.253.jar:deps/integrant-0.8.0.jar:deps/jetty-io-10.0.6.jar:deps/netty-transport-native-unix-common-4.1.68.Final.jar:deps/http2-hpack-10.0.6.jar:deps/zstd-jni-1.5.0-4.jar:deps/regions-2.17.40.jar:deps/selmer-1.12.40.jar:deps/annotations-2.17.40.jar:deps/jackson-annotations-2.12.3.jar:deps/expound-0.8.9.jar:deps/commons-logging-1.2.jar:deps/jackson-datatype-jsr310-2.12.3.jar:deps/xz-1.8.jar:deps/jakarta.activation-2.0.1.jar:deps/protocol-core-2.17.40.jar:deps/netty-nio-client-2.17.40.jar:deps/netty-buffer-4.1.68.Final.jar:deps/buddy-hashers-1.8.1.jar:deps/http2-server-10.0.6.jar:deps/simpleclient_common-0.9.0.jar:deps/jetty-annotations-10.0.6.jar:deps/spec.alpha-0.2.194.jar:deps/netty-codec-http2-4.1.68.Final.jar:deps/jakarta.transaction-api-1.3.2.jar:deps/bcpkix-jdk15on-1.68.jar:deps/environ-1.2.0.jar:deps/gson-2.8.5.jar:deps/transit-clj-1.0.324.jar:deps/transit-java-1.0.343.jar:deps/sdk-core-2.17.40.jar:deps/apache-client-2.17.40.jar:deps/jetty-server-10.0.6.jar:deps/nippy-3.1.1.jar:deps/transit-js-0.8.874.jar:deps/asm-analysis-9.1.jar:deps/netty-resolver-4.1.68.Final.jar:deps/jeromq-0.5.2.jar:deps/core.specs.alpha-0.2.56.jar:deps/java-http-clj-0.4.3.jar:deps/aws-query-protocol-2.17.40.jar:deps/jnacl-1.0.0.jar:deps/buddy-sign-3.4.1.jar:deps/tools.analyzer-1.1.0.jar:deps/scrypt-1.4.0.jar:deps/reactor-core-3.3.20.RELEASE.jar:deps/log4j-api-2.17.0.jar:deps/arns-2.17.40.jar:deps/websocket-jetty-api-10.0.6.jar:deps/primitive-math-0.1.6.jar:deps/datoteka-2.0.0.jar:deps/websocket-jetty-common-10.0.6.jar:deps/clj-ldap-0.0.17.jar:deps/core.cache-1.0.225.jar:deps/linked-1.3.0.jar:deps/websocket-core-server-10.0.6.jar:deps/http-client-spi-2.17.40.jar:deps/s3-2.17.40.jar:deps/jetty-plus-10.0.6.jar:deps/reactive-streams-1.0.3.jar:deps/ring-jetty9-adapter-0.15.2.jar:deps/tools.logging-1.2.3.jar:deps/log4j-core-2.17.0.jar:deps/slf4j-api-2.0.0-alpha1.jar:deps/snappy-0.4.jar:deps/jsoup-1.14.2.jar:deps/simpleclient_httpserver-0.9.0.jar:deps/tools.analyzer.jvm-1.2.2.jar:deps/jetty-alpn-server-10.0.6.jar:deps/pretty-spec-0.1.4.jar:deps/ring-servlet-1.9.2.jar:deps/log4j-jul-2.17.0.jar:deps/asm-tree-9.1.jar:deps/camel-snake-kebab-0.4.2.jar:deps/netty-reactive-streams-2.0.5.jar:deps/netty-codec-http-4.1.68.Final.jar:deps/cuerdas-2021.05.29-0.jar:deps/transit-cljs-0.8.269.jar:deps/third-party-jackson-core-2.17.40.jar:deps/log4j-web-2.17.0.jar:deps/java.data-1.0.86.jar:deps/encore-3.9.2.jar:deps/data.json-2.3.1.jar:deps/simpleclient_hotspot-0.9.0.jar:deps/jsonista-0.3.3.jar:deps/cheshire-5.10.0.jar:deps/clojurescript-1.10.844.jar:deps/aws-xml-protocol-2.17.40.jar:deps/HikariCP-5.0.0.jar:deps/netty-transport-4.1.68.Final.jar:deps/websocket-core-common-10.0.6.jar:deps/json-simple-1.1.1.jar:deps/websocket-servlet-10.0.6.jar:deps/crypto-equality-1.0.0.jar:deps/jetty-http-10.0.6.jar:deps/msgpack-0.6.12.jar:deps/postgresql-42.2.23.jar:deps/tools.reader-1.3.6.jar:deps/data.priority-map-1.1.0.jar:deps/profiles-2.17.40.jar:deps/commons-io-2.10.0.jar:deps/jetty-jndi-10.0.6.jar:deps/json-utils-2.17.40.jar:deps/asm-commons-9.1.jar:deps/sentry-5.1.2.jar:deps/netty-transport-native-epoll-4.1.68.Final-linux-x86_64.jar:deps/ring-core-1.9.4.jar:deps/reitit-core-0.5.15.jar:deps/buddy-core-1.10.1.jar:deps/closure-compiler-unshaded-v20210202.jar:deps/lettuce-core-6.1.5.RELEASE.jar:deps/dependency-0.2.1.jar:deps/pretty-1.1.1.jar:deps/core.rrb-vector-0.1.1.jar:deps/uri-1.4.70.jar:deps/javassist-3.18.1-GA.jar:deps/jetty-security-10.0.6.jar:deps/jakarta.annotation-api-1.3.5.jar:deps/jaxb-api-2.3.0.jar:deps/jetty-util-10.0.6.jar:deps/netty-reactive-streams-http-2.0.5.jar:deps/commons-codec-1.15.jar:deps/commons-fileupload-1.4.jar:deps/tools.cli-1.0.206.jar:deps/google-closure-library-0.0-20201211-3e6c510d.jar:deps/jackson-core-2.12.3.jar:deps/tigris-0.1.2.jar:deps/jackson-dataformat-cbor-2.10.2.jar:deps/fipp-0.6.24.jar:deps/aws-core-2.17.40.jar:deps/ring-codec-1.1.3.jar:deps/core.async-1.5.648.jar:deps/bcprov-jdk15on-1.68.jar:deps/unboundid-ldapsdk-5.1.1.jar:deps/meta-merge-1.0.0.jar:deps/netty-handler-4.1.68.Final.jar:deps/log4j-slf4j18-impl-2.17.0.jar:deps/crypto-random-1.2.1.jar:deps/httpcore-4.4.13.jar:deps/httpclient-4.5.13.jar:deps/simpleclient_jetty-0.9.0.jar:deps/lz4-java-1.8.0.jar:deps/netty-codec-4.1.68.Final.jar:deps/google-closure-library-third-party-0.0-20201211-3e6c510d.jar -Dlog4j2.configurationFile=./log4j2.xml clojure.main -m app.main
2024-06-07 03:55:31 [2024-06-06 19:55:31.439] [clojure-agent-send-off-pool-0] I app.metrics - action="initialize metrics"
2024-06-07 03:55:31 [2024-06-06 19:55:31.450] [clojure-agent-send-off-pool-0] I app.db - action="initialize connection pool" name="main" uri="postgresql://penpot-postgres/penpot"
2024-06-07 03:55:31 [2024-06-06 19:55:31.622] [clojure-agent-send-off-pool-0] D app.msgbus - action="initialize msgbus" backend="redis"
2024-06-07 03:55:32 [2024-06-06 19:55:32.045] [clojure-agent-send-off-pool-0] D app.util.rlimit - handler="upload-file-media-object" hint="wrapping rlimit" permits="2"
2024-06-07 03:55:32 [2024-06-06 19:55:32.046] [clojure-agent-send-off-pool-1] D app.util.rlimit - handler="update-profile-photo" hint="wrapping rlimit" permits="2"
2024-06-07 03:55:32 [2024-06-06 19:55:32.046] [clojure-agent-send-off-pool-0] D app.util.rlimit - handler="recover-profile" hint="wrapping rlimit" permits="10"
2024-06-07 03:55:32 [2024-06-06 19:55:32.046] [clojure-agent-send-off-pool-1] D app.util.rlimit - handler="register-profile" hint="wrapping rlimit" permits="10"
2024-06-07 03:55:32 [2024-06-06 19:55:32.047] [clojure-agent-send-off-pool-0] D app.util.rlimit - handler="update-profile-password" hint="wrapping rlimit" permits="10"
2024-06-07 03:55:32 [2024-06-06 19:55:32.047] [clojure-agent-send-off-pool-1] D app.util.rlimit - handler="login" hint="wrapping rlimit" permits="10"
2024-06-07 03:55:32 [2024-06-06 19:55:32.177] [clojure-agent-send-off-pool-1] D app.util.retry - hint="wrapping retry" name="create-comment-thread"
2024-06-07 03:55:32 [2024-06-06 19:55:32.177] [clojure-agent-send-off-pool-0] D app.util.rlimit - handler="update-team-photo" hint="wrapping rlimit" permits="2"
2024-06-07 03:55:32 [2024-06-06 19:55:32.178] [clojure-agent-send-off-pool-1] D app.util.rlimit - handler="create-font-variant" hint="wrapping rlimit" permits="5"
2024-06-07 03:55:32 [2024-06-06 19:55:32.180] [clojure-agent-send-off-pool-0] I app.http.session - action="initialize session updater" max-batch-age="PT5M" max-batch-size="200"
2024-06-07 03:55:32 [2024-06-06 19:55:32.254] [clojure-agent-send-off-pool-0] I app.http - msg="starting http server" name="http" port="6060"
2024-06-07 03:55:32 [2024-06-06 19:55:32.335] [clojure-agent-send-off-pool-0] I app.loggers.zmq - bind="tcp://localhost:45556" msg="intializing ZMQ receiver"
2024-06-07 03:55:32 [2024-06-06 19:55:32.338] [clojure-agent-send-off-pool-0] I app.loggers.database - msg="initializing database error persistence"
2024-06-07 03:55:32 [2024-06-06 19:55:32.341] [clojure-agent-send-off-pool-0] I app.loggers.sentry - dsn="null" msg="initializing sentry reporter"
2024-06-07 03:55:32 [2024-06-06 19:55:32.369] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="objects-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.370] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="session-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.370] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="storage-recheck"
2024-06-07 03:55:32 [2024-06-06 19:55:32.370] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="storage-deleted-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.370] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="audit-log-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.371] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="file-media-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.371] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="file-xlog-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.371] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="storage-touched-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.371] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="audit-log-archive"
2024-06-07 03:55:32 [2024-06-06 19:55:32.371] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="tasks-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.372] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="file-offload"
2024-06-07 03:55:32 [2024-06-06 19:55:32.372] [clojure-agent-send-off-pool-1] D app.worker - action="register task" name="telemetry"
2024-06-07 03:55:32 [2024-06-06 19:55:32.372] [clojure-agent-send-off-pool-0] D app.worker - action="register task" name="sendmail"
2024-06-07 03:55:32 [2024-06-06 19:55:32.373] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="file-media-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.374] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 * * * ?" id="file-xlog-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.374] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="storage-deleted-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.375] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="storage-touched-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.375] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="session-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.376] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 * * * ?" id="storage-recheck"
2024-06-07 03:55:32 [2024-06-06 19:55:32.376] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="objects-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.376] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 0 * * ?" id="tasks-gc"
2024-06-07 03:55:32 [2024-06-06 19:55:32.377] [clojure-agent-send-off-pool-0] D app.worker - action="initialize scheduled task" cron="0 0 */6 * * ?" id="telemetry"
2024-06-07 03:55:32 [2024-06-06 19:55:32.384] [clojure-agent-send-off-pool-0] I app.worker - action="start worker" name="worker" queue="default"
2024-06-07 03:55:32 [2024-06-06 19:55:32.385] [clojure-agent-send-off-pool-0] I app.srepl - host="127.0.0.1" msg="initializing server repl" name="main" port="6062"
2024-06-07 03:55:32 [2024-06-06 19:55:32.386] [clojure-agent-send-off-pool-0] I app.main - msg="welcome to penpot" version="1.10.4-beta-6103-gbdfea7cda"

```

**Comment by lingy-Mg** [comment]
![image](https://github.com/penpot/penpot/assets/4111244/12db4f91-81f0-404a-a749-c5c042acab4c)

**Comment by Hochan666** [comment]
解决了没，什么问题。我也是一样的Docker部署后打不开

**Comment by raishid** [comment]
same

**Comment by Jackiexiong** [comment]
me too!

**Comment by ShuaiZePing** [comment]
me  too

**Comment by lingy-Mg** [comment]
并没有解决 
Not resolved

**Comment by vaminakov** [comment]
This problem is not limited to docker-compose. Same on self-hosted

**Comment by superalex** [comment]
@q349980363 I've just done a clean docker installation with this docker compose https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml and it works perfectly

Your problem is when you try to register a user?, when you try to login?, it would be useful to see your docker-compose.yaml, sometimes this kind of errors are configuration ones.

@vaminakov same for you, could you show us your docker-compose file and some screenshots showing the error?

**Comment by vaminakov** [comment]
@superalex 
I don't use docker or docker-compose. Installed as a "classical" web app with default settings.
The error occurs during completely different actions, such as user login, page creation or any other actions. Fixed by pressing Ctrl+F5

**Comment by lingy-Mg** [comment]
> 我刚刚用这个 docker compose https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml 做了一个干净的 docker 安装，它运行良好
> 
> 你的问题是，当你尝试注册一个用户时，当你尝试登录时，查看你的docker-compose.yaml会很有用，有时这种错误是配置错误。
> 
> 对你来说也是一样，你能向我们展示你的docker-compose文件和一些显示错误的屏幕截图吗？

Hello, the default file I am using has not been modified in any way

**Comment by superalex** [comment]
@vaminakov there are a lot of ways of doing it, we would need much more info about the steps you followed exactly, I would suggest using the recommended one here https://help.penpot.app/technical-guide/getting-started/#start-penpot

**Comment by lingy-Mg** [comment]
![image](https://github.com/user-attachments/assets/97a99012-e0ef-4a4f-aac6-51450b4161f9)
The method I am using does not work

> 有很多方法可以做到这一点，我们需要有关您确切遵循的步骤的更多信息，我建议在此处使用推荐的方法 https://help.penpot.app/technical-guide/getting-started/#start-penpot

**Comment by superalex** [comment]
@q349980363 your problem is when you try to register a user?, when you try to login?, what versions of the docker images are you using? (you can know it with something like `docker compose -f docker-compose.yaml images)
`

**Comment by superalex** [comment]
@q349980363 I've seen in your backend logs something like this 

> "2024-06-07 03:55:32 [2024-06-06 19:55:32.386] [clojure-agent-send-off-pool-0] I app.main - msg="welcome to penpot" version="1.10.4-beta-6103-gbdfea7cda"

1.10 is a very very old version, it should be launching the 2.1 version,  I suggest you update your docker images and launch the docker-compose again:

`docker compose -f docker-compose.yaml pull
`

**Comment by lingy-Mg** [comment]
@superalex    
I think I guessed the reason
We are unable to connect to Docker Hub due to network issues
Must go through an agent
The agent may have cached very early libraries

**Comment by lingy-Mg** [comment]
其他人员是否是使用了 阿里云的镜像加速服务?

**Comment by superalex** [comment]
Thank you very much @q349980363 I'm closing the issue, feel free to open it if you find more issues ;)

**Comment by lingy-Mg** [comment]
@superalex  
非常感谢,正确的解决方法是 关闭掉镜像加速 并且删除所有镜像.
重新下载镜像,阿里云中的镜像文件缓存的是过老的了
我现在已经解决了
![image](https://github.com/user-attachments/assets/4f87517a-2ece-49eb-a1cc-47e732241d34)



Thank you very much, the correct solution is to disable mirror acceleration and delete all mirrors.
Download the mirrors again, the mirrors are cached in Aliyun and are too old.
I've solved it now.

**Comment by superalex** [comment]
Great!, thank you very much @q349980363 ! <3

**Comment by vaminakov** [comment]
@superalex I'm using archlinux AUR package, v2.1.1
https://aur.archlinux.org/packages/penpot

**Comment by superalex** [comment]
@vaminakov we don't officaly support that package, I recommend you using the docker installation directly using the docker-compose file ;)

**Comment by vaminakov** [comment]
After some time I managed to fix the problem. The solution was to use 
proxy_set_header Host $host;
instead of
proxy_set_header Host $http_host;
in nginx.
It would be great to add a reference nginx config to the official documentation
