### ISSUE TITLE
bug: When I type Korean letter in the textfield, the application crashes with an internal error page. 

### ISSUE THREAD

**Issue by sangpil** [uxbox/uxbox#4953]
### Steps To Reproduce

1. Select text component on the canvas. 
2. Input some korean letter like "안녕"
3. Text component doesn't display Korean at all
4. Click on the canvas to change the focus
5. The application freezes with an internal error page. 

### Expected behavior

When I type in Korean, the text component should display the Korean language well. 

### Actual behavior

When I type Korean, the text component doesn't display Korean at all. 

When I click on the canvas to change the focus, the application freezes with an internal error page. 

### Screenshots or video

https://github.com/user-attachments/assets/8a317758-323c-4e42-b0db-1da5265ed5e0

### Desktop (please complete the following information)

MacOS , 
Browser : Chrome ( Version 127.0.6533.89 (Official Build) (arm64) )

### Environment (please complete the following information)

https://design.penpot.app/#/workspace/502c5b43-61ea-81d3-8004-9b6747b9ee92/305c74e3-1838-816a-8004-bf62796ca3e7?page-id=305c74e3-1838-816a-8004-bf62796ca3e8

### Frontend Stack Trace

```console
Hint:    Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
Prof ID: 502c5b43-61ea-81d3-8004-9b6747b973a8
Team ID: 502c5b43-61ea-81d3-8004-9b6747b9b8da

Data:
{:hint
 "Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings."}

Trace:
Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
  at H.exports (https://design.penpot.app/js/main.e72e81216-1722415952.js:135:164)
  at H.exports (https://design.penpot.app/js/main.e72e81216-1722415952.js:295:106)
  at Object.resolveComposition (https://design.penpot.app/js/main.e72e81216-1722415952.js:308:108)
  at https://design.penpot.app/js/main.e72e81216-1722415952.js:306:315

Last events:
[":app.main.data.workspace/start-editing-selected"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/initialize-editor-state"
 ":app.main.data.workspace.texts/editor-select-all"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.edition/clear-edition-mode"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.changes/apply-changes-localy"
 ":app.main.data.changes/update-indexes"
 ""
 ":app.main.data.changes/commit"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.changes/commit-changes"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.texts/finalize-editor-state"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.texts/remove-text-modifier"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.events/event"]
```

**Comment by madalenapmelo-kp** [comment]
Hi @sangpil,

This is a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment.

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

In the meantime, as a workaround you can type 1 letter without the IME and you should then be able to use the IME normally.

I'm closing this issue here as this is already being tracked on #4163

**Comment by sangpil** [comment]
Hi @madalenapmelo-kp 

Thank you for letting me know the situation. 🫡
I hope these issue will fix someday.
