### ISSUE TITLE
bug: Project unusable after adding minimalist-wireframing-kit to project

### ISSUE THREAD

**Issue by rfolo9li** [uxbox/uxbox#5220]
### Steps To Reproduce

1. Download [minimalist-wireframing-kit](https://github.com/penpot/penpot-files/raw/main/minimalist-wireframing-kit.penpot)
2. Go to projects
3. Click on '...'
4. Click on 'import penpot files'
5. Select the downloaded 'minimalist-wireframing-kit' file
6. Add the library to a project (Assets/Libraries/Add)

### Expected behavior

The project should open as expected.

### Actual behavior

- A generic red error message is displayed (Something bad happend or the like) 
- on the network console there is an internal server error (status 500) for /api/rpc/query/file
- After reopening the project (e. g. refresh using F5) a big centered "Internal Error" message is shown and **I cannot use the project anymore**
- Several 400 and 500 errors on the network console e. g. for `/api/rpc/query/file-data-for-thumbnail` and `/api/rpc/query/file-thumbnail`
- The library minimalist-wireframing-kit cannot be removed

### Desktop (please complete the following information)

All platforms

### Environment (please complete the following information)

- self-hosted (Debian 11, Docker version 20.10.22, build 3a2c30b)
- Containers:
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS          PORTS                               NAMES
f7af5c5c01de   penpotapp/frontend:latest   "/bin/bash /entrypoi…"   55 minutes ago   Up 55 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp   penpot-penpot-frontend-1
17e2255251cb   penpotapp/backend:latest    "/bin/bash run.sh"       55 minutes ago   Up 55 minutes                                       penpot-penpot-backend-1
aa4154be68bd   postgres:14                 "docker-entrypoint.s…"   55 minutes ago   Up 55 minutes   5432/tcp                            penpot-penpot-postgres-1
24fec9888c96   penpotapp/exporter:latest   "/usr/local/nodejs/b…"   55 minutes ago   Up 55 minutes                                       penpot-penpot-exporter-1
4f58e2bd18f0   redis:7                     "docker-entrypoint.s…"   55 minutes ago   Up 55 minutes   6379/tcp                            penpot-penpot-redis-1
```

### Backend Stack Trace

```console
[2024-10-28 15:44:00.189] E app.http.errors - class org.fressian.TaggedObject cannot be cast to class clojure.lang.Associative (org.fressian.TaggedObject and clojure.lang.Associative are in unnamed module of loader 'app')
java.lang.ClassCastException: class org.fressian.TaggedObject cannot be cast to class clojure.lang.Associative (org.fressian.TaggedObject and clojure.lang.Associative are in unnamed module of loader 'app')
        at clojure.lang.RT.assoc(RT.java:827) ~[penpot.jar:?]
        at clojure.core$assoc__5481.invokeStatic(core.clj:195) ~[penpot.jar:?]
        at clojure.core$assoc__5481.doInvoke(core.clj:192) ~[penpot.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:494) ~[penpot.jar:?]
        at app.common.types.shape$setup_rect_selrect.invokeStatic(shape.cljc:441) ~[penpot.jar:?]
        at app.common.types.shape$setup_rect_selrect.invoke(shape.cljc:435) ~[penpot.jar:?]
        at app.common.pages.migrations$fn__24332$fix_empty_points__24337.invoke(migrations.cljc:88) ~[penpot.jar:?]
        at app.common.pages.migrations$fn__24332$update_object__24341.invoke(migrations.cljc:105) ~[penpot.jar:?]
        at clojure.core$update_vals$fn__8943.invoke(core.clj:8017) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$NodeSeq.kvreduce(PersistentHashMap.java:1307) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$BitmapIndexedNode.kvreduce(PersistentHashMap.java:802) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$NodeSeq.kvreduce(PersistentHashMap.java:1312) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$BitmapIndexedNode.kvreduce(PersistentHashMap.java:802) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$ArrayNode.kvreduce(PersistentHashMap.java:466) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap.kvreduce(PersistentHashMap.java:236) ~[penpot.jar:?]
        at clojure.core$fn__8525.invokeStatic(core.clj:6908) ~[penpot.jar:?]
        at clojure.core$fn__8525.invoke(core.clj:6888) ~[penpot.jar:?]
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175) ~[penpot.jar:?]
        at clojure.core$reduce_kv.invokeStatic(core.clj:6919) ~[penpot.jar:?]
        at clojure.core$update_vals.invokeStatic(core.clj:8018) ~[penpot.jar:?]
        at clojure.core$update_vals.invoke(core.clj:8008) ~[penpot.jar:?]
        at app.common.data$update_vals.invokeStatic(data.cljc:240) ~[penpot.jar:?]
        at app.common.data$update_vals.invoke(data.cljc:235) ~[penpot.jar:?]
        at clojure.core$update.invokeStatic(core.clj:6233) ~[penpot.jar:?]
        at clojure.core$update.invoke(core.clj:6223) ~[penpot.jar:?]
        at app.common.pages.migrations$fn__24332$update_page__24345.invoke(migrations.cljc:114) ~[penpot.jar:?]
        at clojure.core$update_vals$fn__8943.invoke(core.clj:8017) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$NodeSeq.kvreduce(PersistentHashMap.java:1307) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$BitmapIndexedNode.kvreduce(PersistentHashMap.java:802) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap$ArrayNode.kvreduce(PersistentHashMap.java:466) ~[penpot.jar:?]
        at clojure.lang.PersistentHashMap.kvreduce(PersistentHashMap.java:236) ~[penpot.jar:?]
        at clojure.core$fn__8525.invokeStatic(core.clj:6908) ~[penpot.jar:?]
        at clojure.core$fn__8525.invoke(core.clj:6888) ~[penpot.jar:?]
        at clojure.core.protocols$fn__8257$G__8252__8266.invoke(protocols.clj:175) ~[penpot.jar:?]
        at clojure.core$reduce_kv.invokeStatic(core.clj:6919) ~[penpot.jar:?]
        at clojure.core$update_vals.invokeStatic(core.clj:8018) ~[penpot.jar:?]
        at clojure.core$update_vals.invoke(core.clj:8008) ~[penpot.jar:?]
        at app.common.data$update_vals.invokeStatic(data.cljc:240) ~[penpot.jar:?]
        at app.common.data$update_vals.invoke(data.cljc:235) ~[penpot.jar:?]
        at clojure.core$update.invokeStatic(core.clj:6233) ~[penpot.jar:?]
        at clojure.core$update.invoke(core.clj:6223) ~[penpot.jar:?]
        at app.common.pages.migrations$fn__24332.invokeStatic(migrations.cljc:116) ~[penpot.jar:?]
        at app.common.pages.migrations$fn__24332.invoke(migrations.cljc:62) ~[penpot.jar:?]
        at clojure.lang.MultiFn.invoke(MultiFn.java:229) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_data$migrate_fn__24310.invoke(migrations.cljc:33) ~[penpot.jar:?]
        at clojure.lang.LongRange.reduce(LongRange.java:233) ~[penpot.jar:?]
        at clojure.core$reduce.invokeStatic(core.clj:6885) ~[penpot.jar:?]
        at clojure.core$reduce.invoke(core.clj:6868) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_data.invokeStatic(migrations.cljc:34) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_data.invoke(migrations.cljc:26) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_data.invokeStatic(migrations.cljc:27) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_data.invoke(migrations.cljc:26) ~[penpot.jar:?]
        at clojure.core$update.invokeStatic(core.clj:6231) ~[penpot.jar:?]
        at clojure.core$update.invoke(core.clj:6223) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_file.invokeStatic(migrations.cljc:40) ~[penpot.jar:?]
        at app.common.pages.migrations$migrate_file.invoke(migrations.cljc:36) ~[penpot.jar:?]
        at app.rpc.queries.files$retrieve_file.invokeStatic(files.clj:233) ~[penpot.jar:?]
        at app.rpc.queries.files$retrieve_file.invoke(files.clj:229) ~[penpot.jar:?]
        at app.rpc.queries.files$sm$file_data_for_thumbnail.invokeStatic(files.clj:394) ~[penpot.jar:?]
        at app.rpc.queries.files$sm$file_data_for_thumbnail.invoke(files.clj:389) ~[penpot.jar:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:156) ~[penpot.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[penpot.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[penpot.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:421) ~[penpot.jar:?]
        at app.rpc$wrap_dispatch$fn__34165$fn__34166.invoke(rpc.clj:126) ~[penpot.jar:?]
        at promesa.util.SupplierWrapper.get(util.cljc:37) ~[penpot.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**Comment by rfolo9li** [comment]
Ok, after pulling updates (`docker compose -f docker-compose.yaml pull`), the problem seems gone. I was still on a 1.x version. But in my opinion, it is still a bug because importing an incompatible file renders the project unusable. This should never happen.
