### ISSUE TITLE
bug: Internal Error on Large Copy or Component Usage

### ISSUE THREAD

**Issue by aliGhadyani** [uxbox/uxbox#5287]
### Steps To Reproduce

I defined a table component with about 25 sub-componnets and I used it 3 times in my page.
The page get extremlly slow and when I try to change smallest thing I get internal error and when I download the report.txt it says 
```
Hint:    http error
Prof ID: 4f048a45-228b-8055-8005-03d80934a0a5
Team ID: 4f048a45-228b-8055-8005-03d971e072e0

Data:
{:type :validation, :code :request-body-too-large, :hint "http error"}

Trace:
Error: http error
...
```

It's llok like it does heavy job on client side and sends large object to backend and the large body of request causes this issue

### Expected behavior

When I copy a element in same page and paste it be fast as possible and no more overhead and slow-down the project

### Actual behavior

By copy and paste elements project get slower and gets internal error of request-body-too-large

```
Hint:    http error
Prof ID: 4f048a45-228b-8055-8005-03d80934a0a5
Team ID: 4f048a45-228b-8055-8005-03d971e072e0

Data:
{:type :validation, :code :request-body-too-large, :hint "http error"}

Trace:
Error: http error
  at new PENPOT.Ah (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:3425:33)
  at PENPOT.Bh (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:3425:355)
  at PENPOT.Ch (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:3425:308)
  at PENPOT.Ax (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:4373:36)
  at https://172.26.103.51/js/shared.33d51a51d-1730738783.js:4347:236
  at v (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:243:276)
  at Y.q [as _nextOverride] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:243:218)
  at Y.d [as _next] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:150:99)
  at Y.next (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:159:12)
  at Y.next [as _nextOverride] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:221:222)
  at Y.d [as _next] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:150:99)
  at Y.next (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:159:12)
  at Y.next [as _nextOverride] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:243:350)
  at Y.d [as _next] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:150:99)
  at Y.next (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:159:12)
  at Y.next [as _nextOverride] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:221:222)
  at Y.d [as _next] (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:150:99)
  at Y.next (https://172.26.103.51/js/shared.33d51a51d-1730738783.js:159:12)
  at https://172.26.103.51/js/shared.33d51a51d-1730738783.js:151:383

Last events:
[":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.texts/update-position-data"
 ":app.main.data.workspace.texts/resize-text"
 ":app.main.data.workspace.texts/clean-text-modifier"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.persistence/persist-commit"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.events/event"
 ":app.main.data.persistence/update-status"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.texts/commit-position-data"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.shapes/update-shapes"
 ":layout/update"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.texts/commit-resize-text"]
```

### Screenshots or video

![Screenshot (36)](https://github.com/user-attachments/assets/324e9c0d-7ef7-406a-a369-8ea26d9e081e)

### Desktop (please complete the following information)

Chrome Browser, Firefox, MS Edge, Brave, All of them getting same error.

### Environment (please complete the following information)

I use self-hosted deployed by docker compose with 8 core CPU and 16 GB of RAM

**Comment by anyuser** [comment]
I recently also often experience this when pasting multiple boards with 50-100 shapes each (simple ones like circles or rectangles, no components). Pasting the boards one by one works. I'm using the version on https://design.penpot.app.

**Comment by anyuser** [comment]
I tried to pinpoint the issue. In my case it's a specific object that creates the crash. 

Here's an example, pasting this will create the error. It contains "intersection" objects with two ellipses that are *not* overlapping (creating no shape), filled with a gradient.


`
{"~:type":"~:copied-shapes","~:features":{"~#set":["layout/grid","components/v2","fdata/shape-data-type"]},"~:version":57,"~:file-id":"~uf336a94c-01dc-8157-8004-998b616de0cb","~:selected":{"~#ordered-set":["~udd27afe0-ada5-805f-8005-447aaa0340a3"]},"~:objects":{"~udd27afe0-ada5-805f-8005-447aaa0340a3":{"~#shape":{"~:y":-12995.79491745188,"~:transform":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:rotation":0,"~:bool-type":"~:intersection","~:name":"Intersection","~:width":0.01,"~:type":"~:bool","~:points":[{"~#point":{"~:x":-7366,"~:y":-11775}},{"~#point":{"~:x":-7365.99,"~:y":-11775}},{"~#point":{"~:x":-7365.99,"~:y":-11774.99}},{"~#point":{"~:x":-7366,"~:y":-11774.99}}],"~:proportion-lock":false,"~:transform-inverse":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:hidden":false,"~:id":"~udd27afe0-ada5-805f-8005-447aaa0340a3","~:parent-id":"~udd27afe0-ada5-805f-8005-447aaa0340a1","~:frame-id":"~udd27afe0-ada5-805f-8005-447aaa0340a1","~:strokes":[],"~:x":-5589.142232443788,"~:proportion":1,"~:selrect":{"~#rect":{"~:x":-7366,"~:y":-11775,"~:width":0.01,"~:height":0.01,"~:x1":-7366,"~:y1":-11775,"~:x2":-7365.99,"~:y2":-11774.99}},"~:fills":[{"~:fill-color-ref-id":"~u46b3be4f-c762-800c-8004-6ee6329085b9","~:fill-color-ref-file":"~uf336a94c-01dc-8157-8004-998b616de0cb","~:fill-color-gradient":{"~:start-x":0.5403046328938784,"~:start-y":0.48542181852623273,"~:end-x":-0.36396801150032476,"~:end-y":0.4380833090651832,"~:width":1.362331829249944,"~:type":"~:radial","~:stops":[{"~:color":"#ff0063","~:file-id":null,"~:offset":0,"~:opacity":1,"~:id":null},{"~:color":"#003cff","~:file-id":null,"~:offset":1,"~:opacity":1,"~:id":null}]}}],"~:bool-content":[],"~:flip-x":null,"~:height":0.01,"~:flip-y":null,"~:shapes":["~udd27afe0-ada5-805f-8005-447aaa0340a9","~udd27afe0-ada5-805f-8005-447aaa0340aa"]}},"~udd27afe0-ada5-805f-8005-447aaa0340a9":{"~#shape":{"~:y":69,"~:transform":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:rotation":0,"~:grow-type":"~:fixed","~:hide-in-viewer":false,"~:name":"Ellipse","~:width":305,"~:type":"~:circle","~:points":[{"~#point":{"~:x":27,"~:y":69}},{"~#point":{"~:x":332,"~:y":69}},{"~#point":{"~:x":332,"~:y":374}},{"~#point":{"~:x":27,"~:y":374}}],"~:proportion-lock":false,"~:transform-inverse":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:id":"~udd27afe0-ada5-805f-8005-447aaa0340a9","~:parent-id":"~udd27afe0-ada5-805f-8005-447aaa0340a3","~:frame-id":"~udd27afe0-ada5-805f-8005-447aaa0340a1","~:strokes":[],"~:x":27,"~:proportion":1,"~:selrect":{"~#rect":{"~:x":27,"~:y":69,"~:width":305,"~:height":305,"~:x1":27,"~:y1":69,"~:x2":332,"~:y2":374}},"~:fills":[{"~:fill-color":"#003fff","~:fill-opacity":1}],"~:flip-x":null,"~:height":305,"~:flip-y":null}},"~udd27afe0-ada5-805f-8005-447aaa0340aa":{"~#shape":{"~:y":390,"~:transform":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:rotation":0,"~:grow-type":"~:fixed","~:hide-in-viewer":false,"~:name":"Ellipse","~:width":305,"~:type":"~:circle","~:points":[{"~#point":{"~:x":27,"~:y":390}},{"~#point":{"~:x":332,"~:y":390}},{"~#point":{"~:x":332,"~:y":695}},{"~#point":{"~:x":27,"~:y":695}}],"~:proportion-lock":false,"~:transform-inverse":{"~#matrix":{"~:a":1,"~:b":0,"~:c":0,"~:d":1,"~:e":0,"~:f":0}},"~:id":"~udd27afe0-ada5-805f-8005-447aaa0340aa","~:parent-id":"~udd27afe0-ada5-805f-8005-447aaa0340a3","~:frame-id":"~udd27afe0-ada5-805f-8005-447aaa0340a1","~:strokes":[],"~:x":27,"~:proportion":1,"~:selrect":{"~#rect":{"~:x":27,"~:y":390,"~:width":305,"~:height":305,"~:x1":27,"~:y1":390,"~:x2":332,"~:y2":695}},"~:fills":[{"~:fill-color":"#003fff","~:fill-opacity":1}],"~:flip-x":null,"~:height":305,"~:flip-y":null}}},"~:images":{"~#set":[]}}`
