### ISSUE TITLE
bug: Huge performance drop when increasing count of text elements

### ISSUE THREAD

**Issue by aliGhadyani** [uxbox/uxbox#5415]
### Steps To Reproduce

When I have only one page and in that page I use about that 100 text element I see huge slowdown in frontend, even worse when I use component containing text in that count
sometime even I get internal error for invalid string but I used same text moments before with no problem.

### Expected behavior

Text are mostly used and they are lightweight and should not cause of slowdown

### Actual behavior

huge slowdown compare to using svg of that elements

### Screenshots or video

Following I posted 

![penpot bug](https://github.com/user-attachments/assets/a2bd4924-b72b-4e0e-9536-ad55b454fe74)

```
Hint:    Invalid string
Prof ID: 4f048a45-228b-8055-8005-03d84a70178b
Team ID: 4f048a45-228b-8055-8005-03d971e072e0

Data:
{:hint "Invalid string"}

Trace:
TypeError: Invalid string
  at W (https://172.26.103.51/js/main.33d51a51d-1730738783.js:14:443)
  at ka (https://172.26.103.51/js/main.33d51a51d-1730738783.js:14:498)
  at tb.replaceParagraphs (https://172.26.103.51/js/main.33d51a51d-1730738783.js:50:280)
  at insertText (https://172.26.103.51/js/main.33d51a51d-1730738783.js:23:192)
  at HTMLDivElement.<anonymous> (https://172.26.103.51/js/main.33d51a51d-1730738783.js:66:347)

Last events:
[":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.edition/start-edition-mode"
 ":app.main.data.workspace/start-editing-selected"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.texts/focus-editor"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.modal/update-modal-props"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.texts/v2-update-text-editor-styles"
 ":app.main.data.modal/update-modal-props"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.changes/apply-changes-localy"
 ":app.main.data.changes/update-indexes"
 ""
 ":app.main.data.changes/commit"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.changes/commit-changes"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.texts/v2-update-text-shape-content"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.texts/v2-update-text-shape-content"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.texts/remove-text-modifier"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.events/event"]
```

### Desktop (please complete the following information)

Any browser ( latest chrome, edge, firefox, brave, opera )

### Environment (please complete the following information)

I use self-hosted deployed by docker compose with 8 core CPU and 16 GB of RAM

**Comment by aliGhadyani** [comment]
I tried to export and import that project in both self hosted and Penpot public and I get error something went wrong or couldn't import the file
