### ISSUE TITLE
bug: Rearranging grid items in layer view causes crash

### ISSUE THREAD

**Issue by JoltCode** [uxbox/uxbox#5446]
### Steps To Reproduce

1: Add elements to a grid layout
2: Attempt to rearrange the order of an element the layer menu
3: Observe the crash

### Expected behavior

The items should be rearranged.

### Actual behavior

The editor crashes.

### Screenshots or video

<img width="1582" alt="Crashed penpot" src="https://github.com/user-attachments/assets/e2ffcb68-fc91-4ebb-871f-3459099ac5d3">

### Desktop (please complete the following information)

- OS: MacOS
- Arc:
  - Version 1.72.1 (56511)
Chromium Engine Version 131.0.6778.109

### Environment (please complete the following information)

- https://design.penpot.app

### Frontend Stack Trace

```console
Hint:    nth not supported on this type function(a,b,c,d,e,f){this.meta=a;this.xa=b;this.root=c;this.gd=d;this.qd=e;this.__hash=f;this.aa=16123663;this.ba=139268}
Prof ID: HIDDEN
Team ID: HIDDEN

Data:
{:hint
 "nth not supported on this type function(a,b,c,d,e,f){this.meta=a;this.xa=b;this.root=c;this.gd=d;this.qd=e;this.__hash=f;this.aa=16123663;this.ba=139268}"}

Trace:
Error: nth not supported on this type function(a,b,c,d,e,f){this.meta=a;this.xa=b;this.root=c;this.gd=d;this.qd=e;this.__hash=f;this.aa=16123663;this.ba=139268}
  at PENPOT.x (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:3284:451)
  at https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1861:320
  at https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1753:339
  at PENPOT.g.Xb (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:5129:392)
  at PENPOT.Rb (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:3297:261)
  at PENPOT.TS (https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1753:273)
  at https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1861:243
  at https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1862:11
  at j0b (https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:1862:114)
  at Lgc.oZ.ma (https://design.penpot.app/js/main.3cdbd7f38-1731662209.js:2813:405)
  at PENPOT.FTa (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:4389:302)
  at b (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:6991:50)
  at Object.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:6992:463)
  at U.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:160:105)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at d.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:171:42)
  at Object.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:348:198)
  at U.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:160:105)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at Y.next [as _nextOverride] (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:363:301)
  at Y.d [as _next] (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:150:99)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at d.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:171:42)
  at Object.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:6991:133)
  at U.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:160:105)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at t (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:152:277)
  at da._subscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:151:313)
  at da._trySubscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:161:85)
  at da.subscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:161:25)
  at da._subscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:286:105)
  at da._trySubscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:161:85)
  at da.subscribe (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:161:25)
  at PENPOT.Qw (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:4351:470)
  at PENPOT.Rw (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:4352:230)
  at b (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:6991:109)
  at Object.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:6992:463)
  at U.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:160:105)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)
  at d.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:171:42)
  at Object.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:348:198)
  at U.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:160:105)
  at Y._next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:302)
  at Y.next (https://design.penpot.app/js/shared.3cdbd7f38-1731662209.js:159:12)

Last events:
[":app.main.features/initialize"
 ":app.main.data.users/set-current-team"
 ":app.main.data.workspace/bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle-stage-2"
 ":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.plugins/check-open-plugin"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace/relocate-shapes"
 ":app.main.data.workspace/relocate-selected-shapes"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace/set-margins-selected"
 ":app.main.data.events/event"]
```

**Comment by madalenapmelo-kp** [comment]
Hi @JoltCode,

Thanks for reporting this! I haven't been able to reproduce this, could you share a screen recording of the issue? Could you also confirm if you experience this issue when working with other browsers?

**Comment by JoltCode** [comment]
> Hi @JoltCode,
> 
> Thanks for reporting this! I haven't been able to reproduce this, could you share a screen recording of the issue? Could you also confirm if you experience this issue when working with other browsers?

Sure, @madalenapmelo-kp, here you go:

https://github.com/user-attachments/assets/371e3a02-f98d-48b6-8773-328bb92cdfde

I'll check on another browser shortly!

**Comment by JoltCode** [comment]
@madalenapmelo-kp Can confirm, this also happens on Safari.

**Comment by madalenapmelo-kp** [comment]
Hi @JoltCode,

Thanks for confirming! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/9514

**Comment by JoltCode** [comment]
> Hi @JoltCode,
> 
> Thanks for confirming! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/9514

Thank you! 😄

**Comment by madalenapmelo-kp** [comment]
This issue has been fixed and the fix will be released soon!
