### ISSUE TITLE
bug: cannot delete files or pages within files

### ISSUE THREAD

**Issue by patheard** [uxbox/uxbox#5483]
### Steps To Reproduce

When building a frontend Docker image from latest `develop` branch, attempting to delete a file or a page within a file throws a client side error.

1. Build a new `penpotapp/frontend:latest` Docker image from the latest current `develop` branch.
2. Start the docker compose service stack.
3. Register, login and create a blank file.
4. Attempt to delete the file.  Client side error is thrown.
5. Reload and open the file.
6. Add a blank page to the file.
7. Attempt to delete the page.  Client side error is thrown.

### Expected behavior

Files and pages within files can be deleted.

### Actual behavior

Client side errors are thrown when attempting to delete files or pages within files.

### Screenshots or video

https://github.com/user-attachments/assets/5347fd76-e7f0-45b6-ae53-b56f0b902fb5

https://github.com/user-attachments/assets/9071864f-77b7-4d61-894c-3ee59cd3c8cb

### Desktop (please complete the following information)

- Mac (arm64) Sequoia 15.2 
- Chrome 131.0.6778.140

### Environment (please complete the following information)

Local instance running docker compose service stack.  Steps I used to setup the environment:

```sh
git clone git@github.com:penpot/penpot.git
cd penpot
./manage.sh build-frontend-bundle && ./manage.sh build-frontend-docker-images
cd docker/images
docker compose up
```

### Frontend Stack Trace

```console
# ==============================================================
# DELETE FILE
# ==============================================================
Hint:    Cannot read properties of null (reading 'toLowerCase')
Prof ID: e6394203-ad1d-814f-8005-71c4e91d7466
Team ID: --

Data:
{:hint "Cannot read properties of null (reading 'toLowerCase')"}

Trace:
TypeError: Cannot read properties of null (reading 'toLowerCase')
  at PENPOT.Yg (http://localhost:9001/js/shared.-1734528523.js:290:458)
  at M9.I (/js/main-dashboard.-1734528523.js:35:200)
  at PTa (http://localhost:9001/js/shared.-1734528523.js:1230:292)
  at b (http://localhost:9001/js/shared.-1734528523.js:4036:43)
  at Object.next (http://localhost:9001/js/shared.-1734528523.js:4037:463)
  at aF.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:2258)
  at e._next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1644)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at ic.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:7147)
  at Object.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:23948)
  at aF.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:2258)
  at e._next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1644)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at e.next [as _nextOverride] (http://localhost:9001/js/libs.js?ts=1734528611138:592:25684)
  at e.kut [as _next] (http://localhost:9001/js/libs.js?ts=1734528611138:592:1873)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at ic.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:7147)
  at z.next (http://localhost:9001/js/shared.-1734528523.js:4038:38)
  at zK.g (http://localhost:9001/js/shared.-1734528523.js:3754:302)
  at PENPOT.Y.h (http://localhost:9001/js/shared.-1734528523.js:4040:389)
  at Yga (http://localhost:9001/js/shared.-1734528523.js:180:112)
  at PENPOT.Ae.g (http://localhost:9001/js/shared.-1734528523.js:1875:85)
  at q (/js/main-dashboard.-1734528523.js:100:158)
  at http://localhost:9001/js/main.-1734528523.js:2213:145
  at Object.WPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:9876)
  at jPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:10033)
  at VPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:10093)
  at kW (http://localhost:9001/js/libs.js?ts=1734528611138:26:31557)
  at a7 (http://localhost:9001/js/libs.js?ts=1734528611138:26:31975)
  at http://localhost:9001/js/libs.js?ts=1734528611138:26:36908
  at yk (http://localhost:9001/js/libs.js?ts=1734528611138:29:36987)
  at OH (http://localhost:9001/js/libs.js?ts=1734528611138:26:9007)
  at PN (http://localhost:9001/js/libs.js?ts=1734528611138:26:33265)
  at YI (http://localhost:9001/js/libs.js?ts=1734528611138:26:17417)
  at lMe (http://localhost:9001/js/libs.js?ts=1734528611138:26:17200)

Last events:
[":app.plugins/initialize"
 ":app.main.features/initialize"
 ":app.main.data.profile/fetch-profile"
 ":app.main.data.profile/refresh-profile"
 ":app.main/initialize"
 ":app.main.data.profile/profile-fetched"
 ":app.main.data.profile/set-profile"
 ":app.main.router/initialize-router"
 ":app.main.router/initialize-history"
 ":app.main.ui.routes/init-routes"
 ":app.main.data.websocket/initialize"
 ":app.main.data.websocket/opened"
 ":app.main.router/navigate"
 ":app.main.router/navigated"
 ":app.main.data.team/fetch-teams"
 ":app.main.data.team/initialize-team"
 ":app.main.data.team/teams-fetched"
 ":app.main.features/initialize"
 ":app.main.data.team/set-current-team"
 ":app.main.data.team/fetch-members"
 ":app.main.data.team/team-initialized"
 ":app.main.data.comments/retrieve-unread-comment-threads"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.dashboard/fetch-projects"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.dashboard/initialize"
 ":app.main.data.team/members-fetched"
 ":app.main.data.fonts/fonts-loaded"
 ":app.main.data.dashboard/projects-fetched"
 ":app.main.data.dashboard/fetch-recent-files"
 ":app.main.data.dashboard/clear-file-select"
 ":app.main.data.dashboard/recent-files-fetched"
 ":app.main.data.dashboard/set-file-thumbnail"
 ":app.main.data.dashboard/clear-file-select"
 ":app.main.data.dashboard/toggle-file-select"
 ":app.main.data.dashboard/show-file-menu-with-position"
 ":app.main.data.dashboard/hide-file-menu"
 ":app.main.data.modal/show-modal"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.dashboard/delete-file"
 ":app.main.data.notifications/show"
 ":app.main.data.dashboard/clear-file-select"
 ":app.main.data.team/finalize-team"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.dashboard/finalize"
 ":app.main.data.event/event"]



# ==============================================================
# DELETE PAGE IN FILE
# ==============================================================
Hint:    Cannot read properties of undefined (reading 'D')
Prof ID: e6394203-ad1d-814f-8005-71c4e91d7466
Team ID: --

Data:
{:hint "Cannot read properties of undefined (reading 'D')"}

Trace:
TypeError: Cannot read properties of undefined (reading 'D')
  at W3c.d6.I (/js/main-workspace.-1734528523.js:540:43)
  at PTa (http://localhost:9001/js/shared.-1734528523.js:1230:292)
  at b (http://localhost:9001/js/shared.-1734528523.js:4036:43)
  at Object.next (http://localhost:9001/js/shared.-1734528523.js:4037:463)
  at aF.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:2258)
  at e._next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1644)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at ic.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:7147)
  at Object.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:23948)
  at aF.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:2258)
  at e._next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1644)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at e.next [as _nextOverride] (http://localhost:9001/js/libs.js?ts=1734528611138:592:25684)
  at e.kut [as _next] (http://localhost:9001/js/libs.js?ts=1734528611138:592:1873)
  at e.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:1370)
  at ic.next (http://localhost:9001/js/libs.js?ts=1734528611138:592:7147)
  at z.next (http://localhost:9001/js/shared.-1734528523.js:4038:38)
  at zK.g (http://localhost:9001/js/shared.-1734528523.js:3754:302)
  at PENPOT.Y.h (http://localhost:9001/js/shared.-1734528523.js:4040:389)
  at eval (/js/main-workspace.-1734528523.js:1432:395)
  at http://localhost:9001/js/main.-1734528523.js:2213:145
  at Object.WPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:9876)
  at jPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:10033)
  at VPe (http://localhost:9001/js/libs.js?ts=1734528611138:26:10093)
  at kW (http://localhost:9001/js/libs.js?ts=1734528611138:26:31557)
  at a7 (http://localhost:9001/js/libs.js?ts=1734528611138:26:31975)
  at http://localhost:9001/js/libs.js?ts=1734528611138:26:36908
  at yk (http://localhost:9001/js/libs.js?ts=1734528611138:29:36987)
  at OH (http://localhost:9001/js/libs.js?ts=1734528611138:26:9007)
  at PN (http://localhost:9001/js/libs.js?ts=1734528611138:26:33265)
  at YI (http://localhost:9001/js/libs.js?ts=1734528611138:26:17417)
  at lMe (http://localhost:9001/js/libs.js?ts=1734528611138:26:17200)

Last events:
[":app.main.data.workspace/workspace-initialized"
 ":app.main.router/navigate"
 ":app.main.data.common/go-to-workspace"
 ":app.main.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.project/project-fetched"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.changes/apply-changes-localy"
 ":app.main.data.changes/update-indexes"
 ""
 ":app.main.data.changes/commit"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.changes/commit-changes"
 ":app.main.data.workspace/create-page"
 ":app.main.data.persistence/update-status"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.modal/show-modal"
 ":app.main.router/navigate"
 ":app.main.data.common/go-to-workspace"
 ":app.main.router/navigated"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.workspace/delete-page"
 ":app.main.data.team/finalize-team"
 ":app.main.data.persistence/persist-commit"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.project/finalize-project"
 ":app.main.data.workspace.shape-layout/finalize-shape-layout"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.event/event"]
```

### Additional context

1. For the file delete issue, it's because the `:team-id` property is `nil` in the state, which blows up the [`uuid` conversion](https://github.com/penpot/penpot/blob/69008fbb9098967ee92dc30b4dad72e97ea602e7/frontend/src/app/main/data/dashboard.cljs#L382).
2. For the file page delete issue, it looks like the [`go-to-file` function](https://github.com/penpot/penpot/blob/69008fbb9098967ee92dc30b4dad72e97ea602e7/frontend/src/app/main/data/workspace.cljs#L646) was accidentally deleted as part of a recent refactor.
3. This does not occur with the latest published `penpotapp/frontend:latest` image, running on port 80.  I only discovered the bug because I am self-hosting and want to run with the new unprivileged nginx on port 8080.

**Comment by niwinz** [comment]
Thanks for report, the fix for this issue is on https://github.com/penpot/penpot/pull/5467 PR
