### ISSUE TITLE
bug: Non-root copy only allowed inside a copy when changing color

### ISSUE THREAD

**Issue by 0xd3e** [uxbox/uxbox#5484]
### Steps To Reproduce

1. Import the Material Design 3 library (https://penpot.app/penpothub/libraries-templates/material-design-3)
2. Change the color "Primary" under Assets
3. The error occurs

### Expected behavior

The color should change

### Actual behavior

The frontend crashes with a report.

### Desktop (please complete the following information)

- MacOS Sequoia
- Chrome 131.0.6778.140

### Environment (please complete the following information)

- Host: https://design.penpot.app/

### Frontend Stack Trace

```console
Hint:    error on validating file referential integrity
Prof ID: 75aa5258-9a82-8002-8003-a507e949f2aa
Team ID: 75aa5258-9a82-8002-8003-a507e94a52ea
File ID: f4869680-6fe6-80f4-8005-7194e5e8545a

Data:
{:type :validation,
 :code :referential-integrity,
 :hint "error on validating file referential integrity",
 :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
 :details
 [{:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c5debe1a",
                      :name "Background",
                      :type :rect,
                      :x 9625,
                      :y 567,
                      :width 18,
                      :height 18,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c5debe1a",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c5dedf67",
                      :name "Container",
                      :type :frame,
                      :x 9625,
                      :y 567,
                      :width 18,
                      :height 18,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c5dedf67",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c5de08e4",
                      :name "Background",
                      :type :rect,
                      :x 9634,
                      :y 567,
                      :width 18.000000000000227,
                      :height 18.000000000006594,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c5de08e4",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c560c2ba",
                      :name "Background",
                      :type :rect,
                      :x 9274,
                      :y 985.9999999999945,
                      :width 18.000000000000227,
                      :height 18.000000000006366,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c560c2ba",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c5610453",
                      :name "Container",
                      :type :frame,
                      :x 9274,
                      :y 986,
                      :width 18,
                      :height 18,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c5610453",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c515a91b",
                      :name "Background",
                      :type :rect,
                      :x 10455,
                      :y 986,
                      :width 18.000000000000227,
                      :height 18.000000000006594,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c515a91b",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c3c69c48",
                      :name "Background",
                      :type :rect,
                      :x 9625,
                      :y 724,
                      :width 18,
                      :height 18,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c3c69c48",
   :args nil}
  {:code :not-head-copy-not-allowed,
   :hint "Non-root copy only allowed inside a copy",
   :shape
   ##object[Function]{:id #uuid "d815c3bc-f62a-80d3-8005-71e9c3c6c15d",
                      :name "Container",
                      :type :frame,
                      :x 9625,
                      :y 724,
                      :width 18,
                      :height 18,
                      :rotation 0,
                      :selrect ##object[iv]{#, #, #, #, #, #, #, #},
                      :points [# # # #],
                      ...},
   :file-id #uuid "f4869680-6fe6-80f4-8005-7194e5e8545a",
   :page-id #uuid "ef68baf8-3d3e-8095-8002-3699280398e2",
   :shape-id #uuid "d815c3bc-f62a-80d3-8005-71e9c3c6c15d",
   :args nil}]}

Trace:
Error: http error
  at new PENPOT.ah (https://design.penpot.app/js/shared.b8ebbe8c3-1734094164.js:292:33)
  at PENPOT.bh (https://design.penpot.app/js/shared.b8ebbe8c3-1734094164.js:292:355)
  at PENPOT.ch (https://design.penpot.app/js/shared.b8ebbe8c3-1734094164.js:292:308)
  at PENPOT.sUa (https://design.penpot.app/js/shared.b8ebbe8c3-1734094164.js:1242:388)
  at https://design.penpot.app/js/shared.b8ebbe8c3-1734094164.js:1217:236
  at h (https://design.penpot.app/js/libs.js?ts=1734094811986:592:16436)
  at e._ [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:16386)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734094811986:592:1370)
  at https://design.penpot.app/js/libs.js?ts=1734094811986:592:4469

Last events:
[":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.libraries/update-component-thumbnail"
 ":app.main.data.persistence/error"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/discard-persistence-state"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"]
```

### Additional context

It worked for all colors except the following:
- On Primary
- Primary
- On Surface
- On Surface Variant
- Surface

**Comment by madalenapmelo-kp** [comment]
Hi @0xd3e,

Thanks for reporting this! This is already being tracked at issue #5312 and we have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/9326) as well, so I'm closing this one here.
