### ISSUE TITLE
bug: App crashes as soon as I click on anything in the editor

### ISSUE THREAD

**Issue by christophe-lacasse-bfg** [uxbox/uxbox#5485]
### Steps To Reproduce

1. Open PenPot and login
2. Click on any of my existing projects
3. When the project loads, you can click around on the pages and components in the left sidebar without any issue
4. On certain pages, BUT NOT ALL of them, as soon as you click anywhere in the main editor window, it crashes

### Expected behavior

It shouldn/t crash as soon as I click anywhere in the editor

### Actual behavior

The penpot app crashes and display the "Internal Error: Something bad happened" error page

### Screenshots or video

I could provide a video in direct messages if necessary, but I'm not at liberty to share this info with the whole world

### Desktop (please complete the following information)

- MacOS Sonoma 14.7.1
- Firefox version 133.0.3 (Have a colleague using Chrome with the same issue)

### Environment (please complete the following information)

- Host: https://design.penpot.app/

### Frontend Stack Trace

```console
Hint:    a.ka is not a function
Prof ID: a0a8e792-b2d2-818e-8005-5825c546b0e0
Team ID: a0a8e792-b2d2-818e-8005-58261ba13579

Data:
{:hint "a.ka is not a function"}

Trace:
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2029:201
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1937:142
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2029:201
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1937:142
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1989:70
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1937:142
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1989:70
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3798:162
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2029:201
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1780:31
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
via@https://design.penpot.app/js/shared.377f636b8-1734525476.js:248:154
PENPOT.g.th@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2036:58
Yb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:127:45
Bga@https://design.penpot.app/js/shared.377f636b8-1734525476.js:165:88
PENPOT.g.Pb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1990:82
PENPOT.Fb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259
PENPOT.Df.h@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1914:103
PENPOT.g.ha@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1991:247
PENPOT.F.j@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1789:371
PENPOT.Og.v@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:335
d@https://design.penpot.app/js/shared.377f636b8-1734525476.js:286:333
c@https://design.penpot.app/js/shared.377f636b8-1734525476.js:286:227
krd<@/js/main-workspace.377f636b8-1734525476.js:2417:82
Gk@https://design.penpot.app/js/libs.js?ts=1734526108506:27:17031
ek@https://design.penpot.app/js/libs.js?ts=1734526108506:29:3143
QV@https://design.penpot.app/js/libs.js?ts=1734526108506:29:2355
cj@https://design.penpot.app/js/libs.js?ts=1734526108506:29:1897
gY@https://design.penpot.app/js/libs.js?ts=1734526108506:29:47407
pY@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39827
u6e@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39753
Nw@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39601
dk@https://design.penpot.app/js/libs.js?ts=1734526108506:29:35963
Ej@https://design.penpot.app/js/libs.js?ts=1734526108506:29:36768
wd@https://design.penpot.app/js/libs.js?ts=1734526108506:27:3288
bY</Na/<@https://design.penpot.app/js/libs.js?ts=1734526108506:29:34289
VoidFunction*Na@https://design.penpot.app/js/libs.js?ts=1734526108506:29:34265
el@https://design.penpot.app/js/libs.js?ts=1734526108506:29:33954
PV@https://design.penpot.app/js/libs.js?ts=1734526108506:27:19879
bY</IV/<@https://design.penpot.app/js/libs.js?ts=1734526108506:27:19742
PENPOT.Ow/e</<@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1255:225
NUa.prototype.Wi/</<@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3760:332
FUa@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1247:269
NUa.prototype.Wi/<@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3760:259
PENPOT.g.uh/<@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3758:303
FUa@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1247:269
PENPOT.g.uh@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3758:227
PENPOT.g.te@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3757:473
PENPOT.g.ai@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3757:534
PENPOT.TE.h@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1751:56
TE@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1750:124
PENPOT.Og.h@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:110
d@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3781:509
@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:450
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258
_next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:23948
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258
_next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:25684
Lut@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1873
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370
next@https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147
z.next@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3783:38
IK.h@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3770:437
PENPOT.Y.g@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3785:389
Fjd/<@/js/main-workspace.377f636b8-1734525476.js:1619:372
I4e@https://design.penpot.app/js/libs.js?ts=1734526108506:26:9876
P4e@https://design.penpot.app/js/libs.js?ts=1734526108506:26:10033
M4e@https://design.penpot.app/js/libs.js?ts=1734526108506:26:10093
H7@https://design.penpot.app/js/libs.js?ts=1734526108506:26:31557
gV@https://design.penpot.app/js/libs.js?ts=1734526108506:26:31977
bY</cI/<@https://design.penpot.app/js/libs.js?ts=1734526108506:26:36910
Kk@https://design.penpot.app/js/libs.js?ts=1734526108506:29:36987
zj@https://design.penpot.app/js/libs.js?ts=1734526108506:26:9007
cI@https://design.penpot.app/js/libs.js?ts=1734526108506:26:33267
Tk@https://design.penpot.app/js/libs.js?ts=1734526108506:26:17419
X4e@https://design.penpot.app/js/libs.js?ts=1734526108506:26:17200
EventListener.handleEvent*_V@https://design.penpot.app/js/libs.js?ts=1734526108506:26:32776
uI@https://design.penpot.app/js/libs.js?ts=1734526108506:26:32173
bY</Sv/<@https://design.penpot.app/js/libs.js?ts=1734526108506:26:32340
Sv@https://design.penpot.app/js/libs.js?ts=1734526108506:26:32284
bY</so.createRoot@https://design.penpot.app/js/libs.js?ts=1734526108506:29:56075
@https://design.penpot.app/js/main.377f636b8-1734525476.js:4349:438
@https://design.penpot.app/js/main.377f636b8-1734525476.js:4392:4


Last events:
[":app.main.data.dashboard/clear-file-select"
 ":app.main.data.dashboard/toggle-file-select"
 ":app.util.router/navigate"
 ":app.main.data.dashboard/go-to-workspace"
 ":app.util.router/navigated"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.dashboard/finalize"
 ":app.main.data.persistence/initialize-persistence"
 ":app.main.data.plugins/update-plugins-permissions-peek"
 ":app.main.data.workspace.layout/ensure-layout"
 ":app.main.data.workspace/initialize-layout"
 ":app.main.data.notifications/hide"
 ":app.main.features/initialize"
 ":app.main.data.comments/retrieve-comment-threads"
 ":app.main.data.workspace/fetch-bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle"
 ":app.main.data.workspace/initialize-file"
 ":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.features/initialize"
 ":app.main.data.users/set-current-team"
 ":app.main.data.workspace/bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle-stage-2"
 ":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.workspace.libraries/library-thumbnails-fetched"
 ":app.main.data.plugins/check-open-plugin"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-page"
 ":app.util.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"]
```

**Comment by thomasfrobieter** [comment]
+1. When I open an existing Project and try to edit some text by double click it => Internal Error:

```Hint:    2024-07-09T09:56:23.313+02:00 is not ISeqable
Prof ID: 0fb9115d-a827-815a-8001-d2a2c5e87f8c
Team ID: 509c7df0-8f0e-11ec-a2fe-9eafb5cb1e0f

Data:
{:hint "2024-07-09T09:56:23.313+02:00 is not ISeqable"}

Trace:
Error: 2024-07-09T09:56:23.313+02:00 is not ISeqable
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:416)
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:77)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:384
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:218)
  at h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:124)
  at PENPOT.wi.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2137:484)
  at Object.wi (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2135:275)
  at eval (/js/main-workspace.377f636b8-1734525476.js:519:173)
  at F5.O (/js/main-workspace.377f636b8-1734525476.js:519:192)
  at cVa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1258:45)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:15
  at PENPOT.g.ai (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3757:562)
  at PENPOT.TE.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1751:56)
  at Object.TE (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1750:124)
  at PENPOT.Og.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:110)
  at d (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3781:509)
  at Object.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3782:450)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at Object.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:23948)
  at oF.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:2258)
  at e._next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1644)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:25684)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:1370)
  at ic.next (https://design.penpot.app/js/libs.js?ts=1734526108506:592:7147)
  at z.next (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3783:38)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:60
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:67
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:211)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1838:239)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Mg (https://design.penpot.app/js/shared.377f636b8-1734525476.js:284:32)
  at IK.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:36)
  at IK.X (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3771:179)
  at PENPOT.ve.j (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1863:274)
  at PENPOT.Y.l (https://design.penpot.app/js/shared.377f636b8-1734525476.js:3785:452)

Last events:
[":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.edition/start-edition-mode"
 ":app.main.data.workspace/start-editing-selected"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.texts/update-editor-state"
 ":app.main.data.workspace.texts/initialize-editor-state"
 ":app.main.data.workspace.texts/editor-select-all"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.texts/update-text-modifier"
 ":app.main.data.workspace.texts/update-editor"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.guides/move-frame-guides"
 ":app.main.data.workspace.comments/move-frame-comment-threads"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.modifiers/clear-local-transform"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.modifiers/apply-modifiers"
 ":app.main.data.workspace.texts/remove-text-modifier"
 ":app.main.data.events/event"
 ":app.main.data.workspace.modifiers/update-modifiers"
 ":app.main.data.workspace.texts/commit-update-text-modifier"]
```

**Comment by JPustkuchen** [comment]
Yeah this is urgent! Is it on the radar?

**Comment by kylecreate** [comment]
Getting a similar problem here while using [Author-More's Desktop version](https://github.com/author-more/penpot-desktop) and on Firefox 133.0.3.

```Hint:    a.ka is not a function
Prof ID: a1260e62-73b5-80f7-8004-a126a53fec55
Team ID: a1260e62-73b5-80f7-8004-a126a54094d7

Data:
{:hint "a.ka is not a function"}

Trace:
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2029:201
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1989:70
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1937:142
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:3798:162
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1979:213
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
PENPOT.vc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:142:83
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1989:70
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
uc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:141:307
PENPOT.g.ka@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1780:31
PENPOT.gc@https://design.penpot.app/js/shared.377f636b8-1734525476.js:136:75
via@https://design.penpot.app/js/shared.377f636b8-1734525476.js:248:154
PENPOT.g.th@https://design.penpot.app/js/shared.377f636b8-1734525476.js:2036:58
Yb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:127:45
Bga@https://design.penpot.app/js/shared.377f636b8-1734525476.js:165:88
PENPOT.g.Pb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1990:82
PENPOT.Fb@https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259
PENPOT.Df.h@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1914:103
PENPOT.g.ha@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1991:247
PENPOT.F.j@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1789:371
PENPOT.Og.v@https://design.penpot.app/js/shared.377f636b8-1734525476.js:1886:335
d@https://design.penpot.app/js/shared.377f636b8-1734525476.js:286:333
c@https://design.penpot.app/js/shared.377f636b8-1734525476.js:286:227
krd<@/js/main-workspace.377f636b8-1734525476.js:2417:82
Gk@https://design.penpot.app/js/libs.js?ts=1734526108506:27:17031
ek@https://design.penpot.app/js/libs.js?ts=1734526108506:29:3143
QV@https://design.penpot.app/js/libs.js?ts=1734526108506:29:2355
cj@https://design.penpot.app/js/libs.js?ts=1734526108506:29:1897
gY@https://design.penpot.app/js/libs.js?ts=1734526108506:29:47407
pY@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39827
u6e@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39753
Nw@https://design.penpot.app/js/libs.js?ts=1734526108506:29:39601
dk@https://design.penpot.app/js/libs.js?ts=1734526108506:29:35963
Ej@https://design.penpot.app/js/libs.js?ts=1734526108506:29:36768
wd@https://design.penpot.app/js/libs.js?ts=1734526108506:27:3288
bY</Na/<@https://design.penpot.app/js/libs.js?ts=1734526108506:29:34289


Last events:
[":app.main.data.notifications/hide"
 ":app.main.features/initialize"
 ":app.main.data.comments/retrieve-comment-threads"
 ":app.main.data.workspace/fetch-bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle"
 ":app.main.data.workspace/initialize-file"
 ":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.features/initialize"
 ":app.main.data.users/set-current-team"
 ":app.main.data.workspace/bundle-stage-1"
 ":app.main.data.workspace/fetch-bundle-stage-2"
 ":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.plugins/check-open-plugin"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-page"
 ":app.util.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/toggle-collapse"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/toggle-collapse"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.highlight/dehighlight-shape"
 ":app.main.data.workspace.highlight/highlight-shape"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"]
```

**Comment by madalenapmelo-kp** [comment]
Hi @christophe-lacasse-bfg,

Could you send a screen recording to support@penpot.app so that we can look further into this?

**Comment by madalenapmelo-kp** [comment]
Just to let you all know, we are already looking further into this! You can check the progress on Taiga here: https://tree.taiga.io/project/penpot/issue/9612

**Comment by christophe-lacasse-bfg** [comment]
@madalenapmelo-kp Thanks for reaching out!
I have a bad news, good news situation
Bad news: While trying to screen record the issue, I wasn't able to reproduce it anymore 🤷 
Good news: I guess the bug got fixed in the latest deployment!
So I'll close this issue.

**Comment by niwinz** [comment]
We have deployed a workaround the same day. But the final fix, is deployed a few minutes ago. Thanks for reporting
