### ISSUE TITLE
bug: Crash when modifying text with typography library settings

### ISSUE THREAD

**Issue by mfgoes** [uxbox/uxbox#5487]
### Steps To Reproduce

1) Create typography
2) Give it a typography setting from library (first time works)
3) Give existing type item a different typography setting and/or try to adjust the text (crashes)

### Expected behavior

When something has a type (ie H2) and I change it to H1, I don't expect it to crash. 

### Actual behavior

Crash screen: Internal Error
Something bad happened. Please retry the operation and if the problem persists, contact support.

### Screenshots or video

<img width="1021" alt="image" src="https://github.com/user-attachments/assets/a874b962-639d-42fb-b572-a7ff5861d60e" />

_No response_

### Smartphone (please complete the following information)

On Macbook Pro from 2021 running Sonoma, and PC running Win10. 

### Environment (please complete the following information)

design.penpot.app

### Additional context

Hint:    a.lb is not a function
Prof ID: 00c92ba6-454d-8098-8005-73638b34b4f3
Team ID: 00c92ba6-454d-8098-8005-73638b352385

Data:
{:hint "a.lb is not a function"}

Trace:
TypeError: a.lb is not a function
  at PENPOT.Lc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:148:224)
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:476)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
  at Function.e [as g] (https://design.penpot.app/js/shared.377f636b8-1734525476.js:198:177)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:243
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:253)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
  at Function.e [as g] (https://design.penpot.app/js/shared.377f636b8-1734525476.js:198:177)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:379
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at PENPOT.g.Lb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1837:468)
  at PENPOT.sc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:140:356)
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:262)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1846:235)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Df.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1914:103)
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:467)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
  at Function.e [as g] (https://design.penpot.app/js/shared.377f636b8-1734525476.js:198:177)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:379
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:163)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1846:235)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Df.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1914:103)
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:467)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
  at Function.e [as g] (https://design.penpot.app/js/shared.377f636b8-1734525476.js:198:177)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:243
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:253)
  at eJa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:2636:513)
  at Function.e [as g] (https://design.penpot.app/js/shared.377f636b8-1734525476.js:198:177)
  at https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:379
  at PENPOT.ce.Wa (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1891:389)
  at Pga (https://design.penpot.app/js/shared.377f636b8-1734525476.js:176:258)
  at PENPOT.g.ma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1847:24)
  at PENPOT.nc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:139:202)
  at PENPOT.g.Lb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1837:468)
  at PENPOT.sc (https://design.penpot.app/js/shared.377f636b8-1734525476.js:140:356)
  at wd (https://design.penpot.app/js/shared.377f636b8-1734525476.js:164:262)
  at PENPOT.g.Pb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1846:235)
  at PENPOT.Fb (https://design.penpot.app/js/shared.377f636b8-1734525476.js:166:259)
  at PENPOT.Df.h (https://design.penpot.app/js/shared.377f636b8-1734525476.js:1914:103)
  at Dma (https://design.penpot.app/js/shared.377f636b8-1734525476.js:361:467)

Last events:
[":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.shapes/update-shapes"
 ":layout/update"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.texts/commit-resize-text"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.workspace.shape-layout/update-layout-positions"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.edition/clear-edition-mode"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.modal/update-modal-props"
 ":app.main.data.persistence/update-status"
 ":app.main.data.workspace.viewport/update-viewport-position"
 ":app.main.data.persistence/persist-commit"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.persistence/commit-persisted"
 ":app.main.data.persistence/discard-commit"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-file-revn"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-layout"
 ":app.util.router/navigated"
 ":app.main.data.workspace.layout/ensure-layout"
 ":app.main.data.workspace/initialize-layout"
 ":app.main.data.workspace/set-assets-section-open"
 ":app.main.data.workspace/unselect-all-assets"
 ":app.main.data.events/event"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.shapes/update-shapes"
 ":app.main.data.workspace.texts/update-text-attrs"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.texts/apply-typography"
 ":app.main.data.workspace/unselect-all-assets"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"]

**Comment by madalenapmelo-kp** [comment]
Hi @mfgoes,

Thanks for reporting this! This is already being tracked at issue #5486 and on Taiga here: https://tree.taiga.io/project/penpot/issue/9612 so I'm closing this issue here but you can stay up to date with the progress there!
