### ISSUE TITLE
bug: Pending components after component deletion

### ISSUE THREAD

**Issue by malliaridis** [uxbox/uxbox#5496]
### Steps To Reproduce

1. Create multiple components
2. Use the components (see additional context)
3. Delete the components all together

### Expected behavior

All deleted components are properly deleted.

### Actual behavior

Some components stay in the assets and are not deletable. Trying to delete them causes internal error.

### Screenshots or video

![image](https://github.com/user-attachments/assets/dbc4d159-ee9a-4838-92fb-86a63119053b)
![image](https://github.com/user-attachments/assets/08b00bd9-eb4a-4e28-ad50-0e248d415fb9)

### Desktop (please complete the following information)

- Windows 11, Chrome browser (131.0.6778.205)

### Environment (please complete the following information)

https://design.penpot.app/

### Frontend Stack Trace

```console
Hint:    http error
Prof ID: f336a94c-01dc-8157-8004-89f644d64de0
Team ID: 502c5b43-61ea-81d3-8004-89f6bad90f4a

Data:
{:type :validation, :code :params-validation, :hint "http error"}

Errors:
[{:path [:changes 0 0 0 :del-obj :page-id 0],
  :in [:changes 0 :page-id],
  :schema :app.common.schema/uuid,
  :value nil}]

Value:
{:features #{"plugins/runtime" "layout/grid" "styles/v2" "components/v2" "fdata/shape-data-type"},
 :session-id #uuid "2b1aa375-35f6-807f-8005-796468de90e1",
 :revn 772,
 :vern 0,
 :id #uuid "d72c757d-42c5-8058-8005-796475bb6002",
 :commit-id #uuid "2b1aa375-35f6-807f-8005-798eb4e34113",
 :changes [{:type :del-obj, :page-id nil, :id #uuid "2b1aa375-35f6-807f-8005-7974d3d2d2b6"}],
 :origin :app.main.data.workspace.libraries/delete-component,
 :created-at #app/instant "2024-12-24T14:55:28.141Z"}

Trace:
Error: http error
  at new PENPOT.$g (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:97)
  at PENPOT.ah (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:419)
  at PENPOT.bh (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:372)
  at PENPOT.rUa (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:1262:410)
  at https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:1237:242
  at h (https://design.penpot.app/js/libs.js?ts=1734946515493:592:16436)
  at e._ [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:16386)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at https://design.penpot.app/js/libs.js?ts=1734946515493:592:4469

Last events:
[":app.main.data.workspace.viewport/update-viewport-position"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace/unselect-all-assets"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.workspace.undo/start-undo-transaction"
 ":app.main.data.workspace.thumbnails/clear-thumbnail"
 ":app.main.data.comments/detach-comment-thread"
 ":app.main.data.changes/apply-changes-localy"
 ":app.main.data.changes/update-indexes"
 ""
 ":app.main.data.changes/commit"
 ":app.main.data.workspace.undo/append-undo"
 ":app.main.data.changes/commit-changes"
 ":layout/update"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.libraries/delete-component"
 ":app.main.data.workspace.libraries/set-updating-library"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.libraries/sync-file"
 ":app.main.data.workspace.undo/commit-undo-transaction"
 ":app.main.data.workspace.shape-layout/update-layout-positions"
 ":app.main.data.workspace.thumbnails/update-thumbnail"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.persistence/update-status"
 ":app.main.data.workspace.thumbnails/assoc-thumbnail"
 ":app.main.data.workspace.selection/deselect-all"
 ":app.main.data.workspace.selection/handle-area-selection"
 ":app.main.data.workspace.selection/select-shapes-by-current-selrect"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.selection/update-selrect"
 ":app.main.data.workspace.undo/check-open-transactions"
 ":app.main.data.persistence/persist-commit"
 ":app.main.data.persistence/run-persistence-task"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/append-commit"
 ":app.main.data.persistence/error"
 ":app.main.data.persistence/update-status"
 ":app.main.data.persistence/discard-persistence-state"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"]
```

### Additional context

It is unclear if the components were in use at the moment of deletion, but likely not. The deletion caused an inconsistent state between the frontend and backend. The displayed components were previously populated with content, the image (after deletion) shows no content though.

**Comment by madalenapmelo-kp** [comment]
Hi @malliaridis,

Thanks for reporting this! I haven't been able to reproduce this issue, could you please share a screen recording of the steps leading up to it so that we can look further into it?

Could you also confirm if the issue happens when working with other browsers?

**Comment by malliaridis** [comment]
I tried to reproduce this and provide more information, but I am not sure what the exact constraints were that caused these broken components. below is the penpot file that contains these components, if that helps.

Perhaps it is related to some file syncing issue, but I really can't tell.

[penpot-file-reduced.penpot.txt](https://github.com/user-attachments/files/18260964/penpot-file-reduced.penpot.txt)

Just remove the suffix `.txt` as GitHub does not allow `.penpot` file attachments.

**Comment by madalenapmelo-kp** [comment]
Hi @malliaridis,

Thanks for sending the file! We've added this to our backlog on Taiga so that we can look further into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/9623

**Comment by radziszcze-git** [comment]
I believe I experienced the same issue today: when I selected a variant of a component, and attempted to delete it, Penpot threw the 'Something went wrong' screen. When I entered the component again, the supposedly deleted variant was still there.

The bug can be reproduced each time I repeat the scenario, so if you need logs from me, let me know.
