### ISSUE TITLE
bug: Error while exporting assets from design

### ISSUE THREAD

**Issue by xgrid-ayoubkhan558** [uxbox/uxbox#5499]
### Steps To Reproduce

Simply export any assets from design and you will get error.

also why its too difficult to report bugs, means what is backend trace, what is frontend trace, where to get these?

### Expected behavior

When we click export image it should export that image in particular format.

### Actual behavior

When I select any layer in design and click on Export element button it shows me internal error.

### Screenshots or video

![image](https://github.com/user-attachments/assets/64437941-717a-45c1-abeb-e87eb870b7c7)

### Desktop (please complete the following information)

Windows 11
Chrome: Version 131.0.6778.205 (Official Build) (64-bit)

### Frontend Stack Trace

```console
Hint:    locator.waitFor: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#screenshot-afba5c25-cd34-803c-8005-6ed668961d55') to be visible

Prof ID: d72c757d-42c5-8058-8005-792f5822fcb9
Team ID: --

Data:
{:type :server-error,
 :hint
 "locator.waitFor: Timeout 10000ms exceeded.\nCall log:\n  - waiting for locator('#screenshot-afba5c25-cd34-803c-8005-6ed668961d55') to be visible\n"}

Trace:
Error: http error
  at new PENPOT.$g (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:97)
  at PENPOT.ah (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:419)
  at PENPOT.bh (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:299:372)
  at PENPOT.rUa (https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:1262:410)
  at https://design.penpot.app/js/shared.d6f98a6c7-1734945897.js:1237:242
  at h (https://design.penpot.app/js/libs.js?ts=1734946515493:592:16436)
  at e._ [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:16386)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:16499)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at e.next [as _nextOverride] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:13985)
  at e.Lut [as _next] (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1873)
  at e.next (https://design.penpot.app/js/libs.js?ts=1734946515493:592:1370)
  at https://design.penpot.app/js/libs.js?ts=1734946515493:592:4469

Last events:
[":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.exports.assets/request-simple-export"
 ":app.main.data.events/event"
 ":app.main.data.exports.assets/clear-export-state"
 ":app.main.data.viewer/finalize"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"
 ":app.main.data.viewer/fetch-bundle"
 ":app.main.data.viewer/fetch-comment-threads"
 ":app.main.data.viewer/initialize"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.features/initialize"
 ":app.util.router/navigate"
 ":app.main.data.viewer/update-zoom-querystring"
 ":app.main.data.viewer/zoom-to-fill"
 ":app.util.router/navigate"
 ":app.main.data.viewer/go-to-frame-by-index"
 ":app.main.data.viewer/bundle-fetched"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.viewer/set-viewport-size"
 ":app.util.router/navigate"
 ":app.main.data.viewer/update-zoom-querystring"
 ":app.main.data.viewer/zoom-to-fill"
 ":app.util.router/navigate"
 ":app.main.data.viewer/update-zoom-querystring"
 ":app.main.data.viewer/zoom-to-fill"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.viewer/hover-shape"
 ":app.main.data.viewer/select-shape"
 ":app.main.data.exports.assets/request-simple-export"
 ":app.main.data.events/event"
 ":app.main.data.exports.assets/clear-export-state"
 ":app.main.data.viewer/finalize"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"]
```

**Comment by madalenapmelo-kp** [comment]
Hi @xgrid-ayoubkhan558,

I haven't been able to reproduce this issue, could you let me know if you are trying to export a single element or multiple elements at once? Could you also let me know which format you are trying to export to?

If you could share a screen recording of this issue that would be really helpful!

**Comment by xgrid-ayoubkhan558** [comment]
In view mode this error occurs.
https://www.loom.com/share/41b2689faffd4d4a9816e4f8eb0d2c58?sid=f760002e-5553-4564-967e-3fc7b127dea2

**Comment by madalenapmelo-kp** [comment]
Is this happening with this image only or does it happen when you try to export other images as well?

**Comment by xgrid-ayoubkhan558** [comment]
> Is this happening with this image only or does it happen when you try to export other images as well?

It happens with everything, I tried to export svg, raster graphics like png, jpg's  and text layers.

**Comment by madalenapmelo-kp** [comment]
Could you send the .penpot file where you are experiencing this to support@penpot.app so that we can continue to look into this?

**Comment by xgrid-ayoubkhan558** [comment]
> Could you send the .penpot file where you are experiencing this to [support@penpot.app](mailto:support@penpot.app) so that we can continue to look into this?

I'm not allowed to share the file, but this bug should be resolved.

**Comment by dawe-rgb** [comment]
Hello! Since updating my self-hosted version of Penpot from 2.3 to 2.4 yesterday, I have been experiencing an issue with the Export function. The problem occurs with every board I try to export—it seems the connection to the export renderer isn’t working. Is there any chance this can be resolved soon? Thank you so much for creating such an amazing tool—I absolutely love Penpot!

@madalenapmelo-kp

```
Hint:    page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=02f4a495-591e-80d5-8005-8a8c63fd8fe7&page-id=02f4a495-591e-80d5-8005-8a8c63fd8fe8&object-id=53c805da-733e-800a-8005-8a8c65739309&route=objects
Call log:
  - navigating to "http://penpot-frontend/render.html?file-id=02f4a495-591e-80d5-8005-8a8c63fd8fe7&page-id=02f4a495-591e-80d5-8005-8a8c63fd8fe8&object-id=53c805da-733e-800a-8005-8a8c65739309&route=objects", waiting until "networkidle"

Prof ID: 3946e3d5-b561-8001-8004-da2c099b2acc
Team ID: 3946e3d5-b561-8001-8004-da2c099d3f87

Data:
{:type :server-error,
 :hint
 "page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=02f4a495-591e-80d5-8005-8a8c63fd8fe7&page-id=02f4a495-591e-80d5-8005-8a8c63fd8fe8&object-id=53c805da-733e-800a-8005-8a8c65739309&route=objects\nCall log:\n  - navigating to \"http://penpot-frontend/render.html?file-id=02f4a495-591e-80d5-8005-8a8c63fd8fe7&page-id=02f4a495-591e-80d5-8005-8a8c63fd8fe8&object-id=53c805da-733e-800a-8005-8a8c65739309&route=objects\", waiting until \"networkidle\"\n"}

Trace:
Error: http error
  at new PENPOT.$g (https://penpot.weberruss.com/js/shared.60af8d0bc-1736258199.js:299:97)
  at PENPOT.ah (https://penpot.weberruss.com/js/shared.60af8d0bc-1736258199.js:299:419)
  at PENPOT.bh (https://penpot.weberruss.com/js/shared.60af8d0bc-1736258199.js:299:372)
  at PENPOT.sUa (https://penpot.weberruss.com/js/shared.60af8d0bc-1736258199.js:1263:410)
  at https://penpot.weberruss.com/js/shared.60af8d0bc-1736258199.js:1237:242
  at h (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:16436)
  at e._ [as _nextOverride] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:16386)
  at e.Lut [as _next] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1873)
  at e.next (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1370)
  at e.next [as _nextOverride] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:13985)
  at e.Lut [as _next] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1873)
  at e.next (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1370)
  at e.next [as _nextOverride] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:16499)
  at e.Lut [as _next] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1873)
  at e.next (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1370)
  at e.next [as _nextOverride] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:13985)
  at e.Lut [as _next] (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1873)
  at e.next (https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:1370)
  at https://penpot.weberruss.com/js/libs.js?ts=1736258776106:592:4469

Last events:
[":app.main.data.workspace/bundle-stage-2"
 ":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.data.workspace.notifications/handle-presence"
 ":app.main.data.workspace.notifications/initialize"
 ":app.main.data.workspace.shape-layout/initialize"
 ":app.main.data.fonts/load-team-fonts"
 ":app.main.data.workspace/bundle-fetched"
 ":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.data.fonts/team-fonts-loaded"
 ":app.main.data.workspace/workspace-data-loaded"
 ":app.main.data.workspace.libraries/library-thumbnails-fetched"
 ":app.main.data.workspace/libraries-fetched"
 ":app.main.data.plugins/check-open-plugin"
 ":app.main.data.workspace.fix-deleted-fonts/fix-deleted-fonts"
 ":app.main.data.workspace.fix-broken-shapes/fix-broken-shapes"
 ":app.main.data.workspace/workspace-initialized"
 ":app.util.router/navigate"
 ":app.main.data.workspace/go-to-page"
 ":app.util.router/navigated"
 ":app.main.data.workspace/preload-data-uris"
 ":app.main.data.workspace.thumbnails/watch-state-changes"
 ":app.main.data.workspace.libraries/watch-component-changes"
 ":app.main.data.workspace/initialize-page"
 ":app.main.data.workspace.viewport/initialize-viewport"
 ":app.main.data.shortcuts/push-shortcuts"
 ":app.main.data.plugins/save-plugin-permissions-peek"
 ":app.main.data.events/event"
 ":app.main.data.modal/show-modal"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.users/mark-onboarding-as-viewed"
 ":app.main.data.users/fetch-profile"
 ":app.main.data.users/profile-fetched"
 ":app.main.data.workspace.collapse/expand-all-parents"
 ":app.main.data.workspace.selection/select-shape"
 ":app.main.data.workspace.transforms/start-move-selected"
 ":app.main.data.workspace.viewport/finish-panning"
 ":app.main.data.workspace.zoom/finish-zooming"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.exports.assets/request-simple-export"
 ":app.main.data.events/event"
 ":app.main.data.workspace.guides/set-hover-guide"
 ":app.main.data.exports.assets/clear-export-state"
 ":app.main.data.workspace.colors/stop-picker"
 ":app.main.data.modal/hide-modal"
 ":app.main.data.notifications/hide"
 ":app.main.data.workspace.notifications/finalize"
 ":app.main.data.workspace.shape-layout/finalize"
 ":app.main.data.workspace/finalize-file"
 ":app.main.data.workspace/finalize-page"
 ":app.main.data.shortcuts/pop-shortcuts"
 ":app.main.data.events/event"]
```

**Comment by eeropic** [comment]
Have the same issue as @dawe-rgb, the http://penpot-frontend routing is broken somehow
so export not working after upgrading to 2.4 (self-hosted)

**Comment by rwam** [comment]
Same issue here after upgrading to vs. 2.4. Besides of the frontend related stack trace I can provide another stack trace from the **penpot-exporter** container:

```shell
2025-01-13 14:11:45 DBG [app.handlers] hint="process-request", cmd=:export-shapes
2025-01-13 14:11:45 INF [app.browser] origin="factory", action="create", browser-id=12
2025-01-13 14:11:45 INF [app.browser] origin="factory", action="validate", browser-id=12, obj=#object[Browser [object Object]]
2025-01-13 14:11:45 TRC [app.browser] hint="exec:handle:start", browser-id=12
2025-01-13 14:11:45 INF [app.renderer.bitmap] uri=#lambdaisland/uri "http://penpot-frontend/render.html?file-id=1a8dbf0c-e135-804c-8005-9327f8bd6d57&page-id=1a8dbf0c-e135-804c-8005-9327f8bd6d58&object-id=9cb91ca2-2a93-80ba-8005-93280bb9d92a&route=objects"
2025-01-13 14:11:45 INF [app.browser] origin="factory", action="destroy", browser-id=12
2025-01-13 14:11:45 ERR [app.handlers.export-shapes] hint="unexpected error on export multiple"
2025-01-13 14:11:45   page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=1a8dbf0c-e135-804c-8005-9327f8bd6d57&page-id=1a8dbf0c-e135-804c-8005-9327f8bd6d58&object-id=9cb91ca2-2a93-80ba-8005-93280bb9d92a&route=objects
2025-01-13 14:11:45   Call log:
2025-01-13 14:11:45     - navigating to "http://penpot-frontend/render.html?file-id=1a8dbf0c-e135-804c-8005-9327f8bd6d57&page-id=1a8dbf0c-e135-804c-8005-9327f8bd6d58&object-id=9cb91ca2-2a93-80ba-8005-93280bb9d92a&route=objects", waiting until "networkidle"
2025-01-13 14:11:45   
2025-01-13 14:11:45       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:75153:18)
2025-01-13 14:11:45       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$2 (/opt/penpot/exporter/app.js:75147:32)
2025-01-13 14:11:45       at /opt/penpot/exporter/app.js:78836:87
2025-01-13 14:11:45       at Object.resolve (/opt/penpot/exporter/app.js:74161:107)
2025-01-13 14:11:45       at $jscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:73099:78)
2025-01-13 14:11:45       at /opt/penpot/exporter/app.js:73203:30
2025-01-13 14:11:45 ERR [app.handlers] hint="unexpected internal error"
2025-01-13 14:11:45   page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=1a8dbf0c-e135-804c-8005-9327f8bd6d57&page-id=1a8dbf0c-e135-804c-8005-9327f8bd6d58&object-id=9cb91ca2-2a93-80ba-8005-93280bb9d92a&route=objects
2025-01-13 14:11:45   Call log:
2025-01-13 14:11:45     - navigating to "http://penpot-frontend/render.html?file-id=1a8dbf0c-e135-804c-8005-9327f8bd6d57&page-id=1a8dbf0c-e135-804c-8005-9327f8bd6d58&object-id=9cb91ca2-2a93-80ba-8005-93280bb9d92a&route=objects", waiting until "networkidle"
2025-01-13 14:11:45   
2025-01-13 14:11:45       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:75153:18)
2025-01-13 14:11:45       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$2 (/opt/penpot/exporter/app.js:75147:32)
2025-01-13 14:11:45       at /opt/penpot/exporter/app.js:78836:87
2025-01-13 14:11:45       at Object.resolve (/opt/penpot/exporter/app.js:74161:107)
2025-01-13 14:11:45       at $jscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:73099:78)
2025-01-13 14:11:45       at /opt/penpot/exporter/app.js:73203:30
```

**Comment by dawe-rgb** [comment]
Hi @madalenapmelo-kp , do you need additional information, such as a file? Were you able to reproduce the problem?

**Comment by madalenapmelo-kp** [comment]
Hi all,

Thank you for the details! This error seems to be related to Redis not being up and running, could you try restarting the services first? It can happen sometimes that the backend has problems connecting. 

If you are using docker compose, you should also check the docker logs.

**Comment by dawe-rgb** [comment]
Hi @madalenapmelo-kp,

Thank you for your quick reply! I’ve restarted the services several times and also checked the Docker logs. It appears that the Redis server is running:

```
penpot-redis-1      | 1:C 13 Jan 2025 16:06:21.663 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
penpot-redis-1      | 1:C 13 Jan 2025 16:06:21.663 * Redis version=7.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
penpot-redis-1      | 1:C 13 Jan 2025 16:06:21.663 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.664 * monotonic clock: POSIX clock_gettime
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.664 * Running mode=standalone, port=6379.
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * Server initialized
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * Loading RDB produced by version 7.2.7
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * RDB age 4 seconds
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * RDB memory usage when created 0.99 Mb
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * Done loading RDB, keys loaded: 0, keys expired: 0.
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * DB loaded from disk: 0.000 seconds
penpot-redis-1      | 1:M 13 Jan 2025 16:06:21.665 * Ready to accept connections tcp
.
.
.
penpot-exporter-1   | INF [app.util.shell] hint="tmptdir setup", path="/tmp/penpot-exporter"
penpot-exporter-1   | INF [app.core] msg="initializing", public-uri="http://penpot-frontend", version="2.4.1"
penpot-exporter-1   | INF [app.browser] hint="initializing browser pool", opts=#js {:max 5, :min 0, :testOnBorrow true, :evictionRunIntervalMillis 5000, :numTestsPerEvictionRun 5, :acquireTimeoutMillis 10000, :idleTimeoutMillis 10000}
penpot-exporter-1   | INF [app.http] hint="welcome to penpot", module="exporter", flags=#{}, version="2.4.1"
penpot-exporter-1   | INF [app.http] hint="starting http server", port=6061
penpot-exporter-1   | INF [app.redis] hint="redis connection established", uri="redis://penpot-redis/0".
.
.
.
penpot-exporter-1   | DBG [app.handlers] hint="process-request", cmd=:export-shapes
penpot-exporter-1   | INF [app.browser] origin="factory", action="create", browser-id=2
penpot-exporter-1   | INF [app.browser] origin="factory", action="validate", browser-id=2, obj=#object[Browser [object Object]]
penpot-exporter-1   | TRC [app.browser] hint="exec:handle:start", browser-id=2
penpot-exporter-1   | INF [app.renderer.bitmap] uri=#lambdaisland/uri "http://penpot-frontend/render.html?file-id=83bbf316-cddb-8122-8005-8e5ccaaee713&page-id=69b72111-2b7a-8066-8005-9343840ee01b&object-id=69b72111-2b7a-8066-8005-9343997f26c6&route=objects"
penpot-exporter-1   | INF [app.browser] origin="factory", action="destroy", browser-id=2
penpot-exporter-1   | ERR [app.handlers.export-shapes] hint="unexpected error on export multiple"
penpot-exporter-1   |   page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=83bbf316-cddb-8122-8005-8e5ccaaee713&page-id=69b72111-2b7a-8066-8005-9343840ee01b&object-id=69b72111-2b7a-8066-8005-9343997f26c6&route=objects
penpot-exporter-1   |   Call log:
penpot-frontend-1   | 172.18.0.1 - - [13/Jan/2025:16:08:03 +0000] "POST /api/export HTTP/1.1" 500 531 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
penpot-exporter-1   |     - navigating to "http://penpot-frontend/render.html?file-id=83bbf316-cddb-8122-8005-8e5ccaaee713&page-id=69b72111-2b7a-8066-8005-9343840ee01b&object-id=69b72111-2b7a-8066-8005-9343997f26c6&route=objects", waiting until "networkidle"
penpot-exporter-1   |   
penpot-exporter-1   |       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:75153:18)
penpot-exporter-1   |       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$2 (/opt/penpot/exporter/app.js:75147:32)
penpot-exporter-1   |       at /opt/penpot/exporter/app.js:78836:87
penpot-exporter-1   |       at Object.resolve (/opt/penpot/exporter/app.js:74161:107)
penpot-exporter-1   |       at $jscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:73099:78)
penpot-exporter-1   |       at /opt/penpot/exporter/app.js:73203:30
penpot-exporter-1   | ERR [app.handlers] hint="unexpected internal error"
penpot-exporter-1   |   page.goto: net::ERR_CONNECTION_REFUSED at http://penpot-frontend/render.html?file-id=83bbf316-cddb-8122-8005-8e5ccaaee713&page-id=69b72111-2b7a-8066-8005-9343840ee01b&object-id=69b72111-2b7a-8066-8005-9343997f26c6&route=objects
penpot-exporter-1   |   Call log:
penpot-exporter-1   |     - navigating to "http://penpot-frontend/render.html?file-id=83bbf316-cddb-8122-8005-8e5ccaaee713&page-id=69b72111-2b7a-8066-8005-9343840ee01b&object-id=69b72111-2b7a-8066-8005-9343997f26c6&route=objects", waiting until "networkidle"
penpot-exporter-1   |   
penpot-exporter-1   |       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$3 (/opt/penpot/exporter/app.js:75153:18)
penpot-exporter-1   |       at app.browser.nav_BANG_.cljs$core$IFn$_invoke$arity$2 (/opt/penpot/exporter/app.js:75147:32)
penpot-exporter-1   |       at /opt/penpot/exporter/app.js:78836:87
penpot-exporter-1   |       at Object.resolve (/opt/penpot/exporter/app.js:74161:107)
penpot-exporter-1   |       at $jscomp$scope$84173391$24$processNextTick (/opt/penpot/exporter/app.js:73099:78)
penpot-exporter-1   |       at /opt/penpot/exporter/app.js:73203:30
penpot-frontend-1   | 172.18.0.1 - - [13/Jan/2025:16:08:03 +0000] "GET /api/rpc/command/get-file-info?id=83bbf316-cddb-8122-8005-8e5ccaaee713 HTTP/1.1" 200 82 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"


```

**Comment by rwam** [comment]
Hi @madalenapmelo-kp, thanks to dive into this issue but I cannot see anything else in the docker logs. Same results as responded by @dawe-rgb.

**Comment by eeropic** [comment]
My (uneducated) 2 cents is that this is somehow related to the change to unprivileged nginx

I.e. somehow the internal routing is not working correctly

**Comment by devgroop-roland** [comment]
I'm new to Penpot, just spun up a new instance on Elestio. We initially had bad gateway issues until I asked them about the nginx setup - which they resolved and said that there had been a breaking change in the recent version. They didn't elaborate.

However, we now have this connection refused error when attempting to export. I also think it feels like an internal routing issue. Unlike dawe-rgb, we're running 2.3. Export fails on PDF or PNG, individual elements or exporting boards.

Is there a config change we need to make for the render endpoint to work?

**Comment by Sebastix** [comment]
Same issue here since I upgraded to the latest version (2.4.1) with the self-hosted Docker setup.

**Comment by madalenapmelo-kp** [comment]
Please consider that breaking changes were introduced with 2.4.0, could you double-check that you have followed the steps described here: https://github.com/penpot/penpot/blob/develop/CHANGES.md#boom-breaking-changes--deprecations-1

> Breaking changes & Deprecations
> Use [nginx-unprivileged](https://hub.docker.com/r/nginxinc/nginx-unprivileged) as base image for Penpot's frontend docker image. Now all the docker images runs with the same unprivileged user (penpot). Because of that, the default NGINX listen port is now 8080 instead of 80, so you will have to modify your infrastructure to apply this change.
> 
> Redis 7.2 is explicitly pinned in our example docker-compose.yml file. This is done because, starting with the next versions, Redis is no longer distributed under an open-source license. On-premise users are obviously free to upgrade to the version they are using or a more modern one. Keep in mind that if you were using a version other than 7.2, you may have to recreate the volume associated with the Redis container because the 7.2 storage format may not be compatible with what you already have stored on the volume, and Redis may not start. In the near future, we will evaluate whether to move to an open-source version of Redis (such as https://valkey.io/).

**Comment by rwam** [comment]
Hi @madalenapmelo-kp,
sure, without updating the port on the frontend the application won't start. So I can start Penpot and can also work on my projects but exporting fails. And I cannot see any difference in using the pinned version 7.2 for Redis in using `image: redis:7` on my `docker-compose.yaml`. Anything else to double check I could missed?

**Comment by eeropic** [comment]
You can reproduce this (export not working) simply by doing fresh 2.4 install with the current self-hosting guide.
I.e. it is not just about upgrading from 2.3 to 2.4

**Comment by madalenapmelo-kp** [comment]
Hi all,

The team has looked further into this and:
- regarding the problem with the export, you'll need to check the changes in docker-compose and set the proper url in penpot-exporter;
- regarding the problem with the connection to the database, we will publish a fix for this in the next couple of days; until the fix is published, as a workaround, you'll need to use the env var PENPOT_SECRET_KEY (which is commented by default in the docker-compose).

**Comment by Sebastix** [comment]
In my `docker-compose.yaml`

- I already set a var `PENPOT_SECRET_KEY` in the penpot-backend service
- I've added port `8080` to `PENPOT_PUBLIC_URI` in the penpot-exporter service (see https://github.com/penpot/penpot/commit/aa023d847d5ccf0bf004cc97ab32ee7fa2897ca9)

Now the export is working again 👍

**Comment by dawe-rgb** [comment]
Thank you! The export function is now working again with:

> In my `docker-compose.yaml`
> 
> * I already set a var `PENPOT_SECRET_KEY` in the penpot-backend service
> * I've added port `8080` to `PENPOT_PUBLIC_URI` in the penpot-exporter service (see [aa023d8](https://github.com/penpot/penpot/commit/aa023d847d5ccf0bf004cc97ab32ee7fa2897ca9))
> 
> Now the export is working again 👍

**Comment by rwam** [comment]
Confirmed: after changing public uri for the penpot-exporter service the export is working 👍

Thanks @ all 😉

**Comment by madalenapmelo-kp** [comment]
Thank you all for confirming! I'm closing this issue but feel free to open another one if anything else comes up :slightly_smiling_face:
